/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.*;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import org.apache.commons.io.FileUtils;

/**
 *
 * @author BrownBox
 */
public final class FormRegistrasi extends javax.swing.JFrame {
    
    private final Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    String id_anggota;
    String lastCharacterId = "0";
    File file;
    JFileChooser jfc;
    
    /**
     * Creates new form FormRegistrasi
     */
    public FormRegistrasi() {
        initComponents();
        datatable();
        getNextIdAnggota();
    }
    

    protected void aktif(){
        textfieldNama.setEnabled(true);
        textfieldNIS.setEnabled(true);
        textfieldNoTelepon.setEnabled(true);
        textfieldNamaFileFoto.setText("");
        jLabelGambar.setIcon(null); 
        textfieldNama.requestFocus();  
        
    }
    protected void kosong(){
        textfieldNama.setText("");
        textfieldNIS.setText("");
        textfieldNoTelepon.setText("");
        jLabelGambar.setIcon(null);
        textfieldNamaFileFoto.setText("");
        getNextIdAnggota();
    }
    public void getNextIdAnggota(){
        String sql = "SELECT id_anggota FROM anggota ORDER BY id_anggota DESC LIMIT 1";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                id_anggota = hasil.getString("id_anggota");
                System.out.println("id anggota terakhir : "+id_anggota);
                lastCharacterId =  id_anggota.length() > 2 ? id_anggota.substring(id_anggota.length() -1) : id_anggota;
                System.out.println("id anggota terakhir : "+id_anggota);
                System.out.println("ambil 1 karakter terakhir id anggota terakhir : "+lastCharacterId);
            }
        }catch (SQLException e){
                    
        }
                
        // Untuk generate ID Anggota YYYYMMXX
        // XX : Id terakhir
        java.util.Date today = new java.util.Date();
        Calendar cal = Calendar.getInstance();
        cal.setTime(today);
        System.out.println(today);
        int dayOfMonth = cal.get(Calendar.MONTH)+1;
        int dayOfYear = cal.get(Calendar.YEAR);
        System.out.println("dayOfMonth :" + dayOfMonth);
        System.out.println("dayOfYear :" + dayOfYear);
        
        int newId = Integer.parseInt(lastCharacterId) + 1;
        System.out.println("getsubstring :" + newId);
                
        String month = Integer.toString(dayOfMonth);
        String year = Integer.toString(dayOfYear);
        String noIdAnggota = Integer.toString(newId);
        
        String IDAnggota = year+month+noIdAnggota;
        textfieldIDAnggota.setText(IDAnggota);
    }
    
    protected void datatable(){
        Object[] Baris = {"ID Anggota", "Nama", "NIS", 
            "No Telepon"};
        tabmode = new DefaultTableModel(null, Baris);
        tableAnggota.setModel(tabmode);
        String sql = "SELECT id_anggota, nama, nis, no_tlp FROM anggota";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("id_anggota");                
                String b = hasil.getString("nama");
                String c = hasil.getString("nis");
                String d = hasil.getString("no_tlp");
                
                String[] data={a, b, c, d};
                tabmode.addRow(data);
            }
        }catch (SQLException e){
                    
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        labelNama = new javax.swing.JLabel();
        textfieldNama = new javax.swing.JTextField();
        labelNIS = new javax.swing.JLabel();
        textfieldNIS = new javax.swing.JTextField();
        labelNoTelepon = new javax.swing.JLabel();
        textfieldNoTelepon = new javax.swing.JTextField();
        buttonSave = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        labelNama1 = new javax.swing.JLabel();
        textfieldIDAnggota = new javax.swing.JTextField();
        labelKodeBuku = new javax.swing.JLabel();
        textfieldNamaFileFoto = new javax.swing.JTextField();
        jButtonPilihFoto = new javax.swing.JButton();
        buttonClear1 = new javax.swing.JButton();
        labelTitle2 = new javax.swing.JLabel();
        jLabelGambar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        buttonCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAnggota = new javax.swing.JTable();
        labelTitle = new javax.swing.JLabel();
        labelNama2 = new javax.swing.JLabel();
        textfieldCariNamaAnggota = new javax.swing.JTextField();
        buttonCancel = new javax.swing.JButton();
        buttonCetakKartuAnggota = new javax.swing.JButton();
        jPanelPrintAnggota = new javax.swing.JPanel();
        labelTitle1 = new javax.swing.JLabel();
        labelTitle3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelGambar1 = new javax.swing.JLabel();
        jLabelGambar2 = new javax.swing.JLabel();
        jLabelGambar3 = new javax.swing.JLabel();
        labelTitle4 = new javax.swing.JLabel();
        labelTitle6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuLaporan1 = new javax.swing.JMenu();
        jMenuMaster = new javax.swing.JMenu();
        jMenuItemInputDataBuku = new javax.swing.JMenuItem();
        jMenuItemRegistrasiAnggota = new javax.swing.JMenuItem();
        jMenuItemRegistrasiPetugas = new javax.swing.JMenuItem();
        jMenuTransaksi = new javax.swing.JMenu();
        jMenuItemPeminjamanBuku = new javax.swing.JMenuItem();
        jMenuItemPengembalianBuku = new javax.swing.JMenuItem();
        jMenuLaporan = new javax.swing.JMenu();
        jMenuLogout = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrasi Anggota");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNama.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelNama.setForeground(new java.awt.Color(153, 153, 153));
        labelNama.setText("Nama");
        jPanel2.add(labelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        textfieldNama.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldNama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldNamaActionPerformed(evt);
            }
        });
        jPanel2.add(textfieldNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 230, -1));

        labelNIS.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelNIS.setForeground(new java.awt.Color(153, 153, 153));
        labelNIS.setText("NIS");
        jPanel2.add(labelNIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        textfieldNIS.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldNIS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldNIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldNISActionPerformed(evt);
            }
        });
        jPanel2.add(textfieldNIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 230, -1));

        labelNoTelepon.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelNoTelepon.setForeground(new java.awt.Color(153, 153, 153));
        labelNoTelepon.setText("No Telepon");
        jPanel2.add(labelNoTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        textfieldNoTelepon.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldNoTelepon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldNoTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldNoTeleponActionPerformed(evt);
            }
        });
        jPanel2.add(textfieldNoTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 230, -1));

        buttonSave.setBackground(new java.awt.Color(9, 110, 59));
        buttonSave.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonSave.setForeground(new java.awt.Color(255, 255, 255));
        buttonSave.setText("Simpan");
        buttonSave.setBorder(null);
        buttonSave.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });
        jPanel2.add(buttonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        buttonEdit.setBackground(new java.awt.Color(9, 110, 59));
        buttonEdit.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonEdit.setForeground(new java.awt.Color(255, 255, 255));
        buttonEdit.setText("Ubah");
        buttonEdit.setBorder(null);
        buttonEdit.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });
        jPanel2.add(buttonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 80, -1));

        buttonDelete.setBackground(new java.awt.Color(9, 110, 59));
        buttonDelete.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonDelete.setForeground(new java.awt.Color(255, 255, 255));
        buttonDelete.setText("Hapus");
        buttonDelete.setBorder(null);
        buttonDelete.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(buttonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, -1, -1));

        buttonClear.setBackground(new java.awt.Color(9, 110, 59));
        buttonClear.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonClear.setForeground(new java.awt.Color(255, 255, 255));
        buttonClear.setText("Bersihkan");
        buttonClear.setBorder(null);
        buttonClear.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });
        jPanel2.add(buttonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 80, -1));

        labelNama1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelNama1.setForeground(new java.awt.Color(153, 153, 153));
        labelNama1.setText("ID Anggota");
        jPanel2.add(labelNama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        textfieldIDAnggota.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldIDAnggota.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldIDAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldIDAnggotaActionPerformed(evt);
            }
        });
        jPanel2.add(textfieldIDAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 230, -1));

        labelKodeBuku.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelKodeBuku.setForeground(new java.awt.Color(153, 153, 153));
        labelKodeBuku.setText("Foto");
        jPanel2.add(labelKodeBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        textfieldNamaFileFoto.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldNamaFileFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldNamaFileFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldNamaFileFotoActionPerformed(evt);
            }
        });
        jPanel2.add(textfieldNamaFileFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 80, -1));

        jButtonPilihFoto.setBackground(new java.awt.Color(0, 153, 102));
        jButtonPilihFoto.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jButtonPilihFoto.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPilihFoto.setText("Pilih Foto");
        jButtonPilihFoto.setBorder(null);
        jButtonPilihFoto.setPreferredSize(new java.awt.Dimension(75, 30));
        jButtonPilihFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPilihFotoActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonPilihFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 80, 20));

        buttonClear1.setBackground(new java.awt.Color(9, 110, 59));
        buttonClear1.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonClear1.setForeground(new java.awt.Color(255, 255, 255));
        buttonClear1.setText("Bersihkan");
        buttonClear1.setBorder(null);
        buttonClear1.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClear1ActionPerformed(evt);
            }
        });
        jPanel2.add(buttonClear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 80, -1));

        labelTitle2.setBackground(new java.awt.Color(9, 110, 59));
        labelTitle2.setFont(new java.awt.Font("Montserrat SemiBold", 1, 24)); // NOI18N
        labelTitle2.setForeground(new java.awt.Color(9, 110, 59));
        labelTitle2.setText("Registrasi Anggota");
        jPanel2.add(labelTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabelGambar.setOpaque(true);
        jPanel2.add(jLabelGambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 140, 170));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonCari.setBackground(new java.awt.Color(9, 110, 59));
        buttonCari.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonCari.setForeground(new java.awt.Color(255, 255, 255));
        buttonCari.setText("Cari");
        buttonCari.setBorder(null);
        buttonCari.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        tableAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAnggotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAnggota);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 550, 160));

        labelTitle.setBackground(new java.awt.Color(9, 110, 59));
        labelTitle.setFont(new java.awt.Font("Montserrat SemiBold", 1, 24)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(9, 110, 59));
        labelTitle.setText("Daftar Anggota");
        jPanel1.add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        labelNama2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelNama2.setForeground(new java.awt.Color(153, 153, 153));
        labelNama2.setText("Nama Anggota");
        labelNama2.setPreferredSize(new java.awt.Dimension(84, 30));
        jPanel1.add(labelNama2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 100, 130, -1));

        textfieldCariNamaAnggota.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldCariNamaAnggota.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldCariNamaAnggota.setPreferredSize(new java.awt.Dimension(2, 30));
        textfieldCariNamaAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldCariNamaAnggotaActionPerformed(evt);
            }
        });
        jPanel1.add(textfieldCariNamaAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 210, -1));

        buttonCancel.setBackground(new java.awt.Color(9, 110, 59));
        buttonCancel.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonCancel.setForeground(new java.awt.Color(9, 110, 59));
        buttonCancel.setText("Batal");
        buttonCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(9, 110, 59)));
        buttonCancel.setContentAreaFilled(false);
        buttonCancel.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        buttonCetakKartuAnggota.setBackground(new java.awt.Color(9, 110, 59));
        buttonCetakKartuAnggota.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonCetakKartuAnggota.setForeground(new java.awt.Color(255, 255, 255));
        buttonCetakKartuAnggota.setText("Cetak Kartu Anggota");
        buttonCetakKartuAnggota.setBorder(null);
        buttonCetakKartuAnggota.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonCetakKartuAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCetakKartuAnggotaActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCetakKartuAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 190, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 590, 350));

        jPanelPrintAnggota.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPrintAnggota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitle1.setBackground(new java.awt.Color(9, 110, 59));
        labelTitle1.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        labelTitle1.setForeground(new java.awt.Color(9, 110, 59));
        labelTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle1.setText("1045");
        jPanelPrintAnggota.add(labelTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 240, -1));

        labelTitle3.setBackground(new java.awt.Color(9, 110, 59));
        labelTitle3.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        labelTitle3.setForeground(new java.awt.Color(9, 110, 59));
        labelTitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle3.setText("Perpustakaan ");
        jPanelPrintAnggota.add(labelTitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/images/logo_mi.gif"))); // NOI18N
        jPanelPrintAnggota.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 70, 60));

        jLabelGambar1.setOpaque(true);
        jPanelPrintAnggota.add(jLabelGambar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 140, 170));

        jLabelGambar2.setOpaque(true);
        jPanelPrintAnggota.add(jLabelGambar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 140, 170));

        jLabelGambar3.setOpaque(true);
        jPanelPrintAnggota.add(jLabelGambar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 80, 90));

        labelTitle4.setBackground(new java.awt.Color(9, 110, 59));
        labelTitle4.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 14)); // NOI18N
        labelTitle4.setForeground(new java.awt.Color(9, 110, 59));
        labelTitle4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle4.setText("MI Assa'adiyah Attahiriyah");
        jPanelPrintAnggota.add(labelTitle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        labelTitle6.setBackground(new java.awt.Color(9, 110, 59));
        labelTitle6.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        labelTitle6.setForeground(new java.awt.Color(9, 110, 59));
        labelTitle6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle6.setText("NURMANSYAH");
        jPanelPrintAnggota.add(labelTitle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 240, -1));

        getContentPane().add(jPanelPrintAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 580, 210));

        jMenuBar1.setBackground(new java.awt.Color(245, 247, 250));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(76, 40));

        jMenuLaporan1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuLaporan1.setForeground(new java.awt.Color(51, 51, 51));
        jMenuLaporan1.setText("Menu Utama");
        jMenuLaporan1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jMenuLaporan1.setIconTextGap(20);
        jMenuLaporan1.setMargin(new java.awt.Insets(2, 20, 2, 20));
        jMenuLaporan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuLaporan1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuLaporan1);

        jMenuMaster.setBackground(new java.awt.Color(255, 255, 255));
        jMenuMaster.setForeground(new java.awt.Color(51, 51, 51));
        jMenuMaster.setText("Master");
        jMenuMaster.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jMenuMaster.setIconTextGap(20);
        jMenuMaster.setMargin(new java.awt.Insets(2, 20, 2, 20));

        jMenuItemInputDataBuku.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemInputDataBuku.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItemInputDataBuku.setText("Input Data Buku");
        jMenuItemInputDataBuku.setPreferredSize(new java.awt.Dimension(280, 30));
        jMenuItemInputDataBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInputDataBukuActionPerformed(evt);
            }
        });
        jMenuMaster.add(jMenuItemInputDataBuku);

        jMenuItemRegistrasiAnggota.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemRegistrasiAnggota.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItemRegistrasiAnggota.setText("Registrasi Anggota");
        jMenuItemRegistrasiAnggota.setPreferredSize(new java.awt.Dimension(280, 30));
        jMenuItemRegistrasiAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrasiAnggotaActionPerformed(evt);
            }
        });
        jMenuMaster.add(jMenuItemRegistrasiAnggota);

        jMenuItemRegistrasiPetugas.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemRegistrasiPetugas.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItemRegistrasiPetugas.setText("Registrasi Petugas");
        jMenuItemRegistrasiPetugas.setPreferredSize(new java.awt.Dimension(280, 30));
        jMenuItemRegistrasiPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrasiPetugasActionPerformed(evt);
            }
        });
        jMenuMaster.add(jMenuItemRegistrasiPetugas);

        jMenuBar1.add(jMenuMaster);

        jMenuTransaksi.setBackground(new java.awt.Color(255, 255, 255));
        jMenuTransaksi.setForeground(new java.awt.Color(51, 51, 51));
        jMenuTransaksi.setText("Transaksi");
        jMenuTransaksi.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jMenuTransaksi.setIconTextGap(20);
        jMenuTransaksi.setMargin(new java.awt.Insets(2, 20, 2, 20));
        jMenuTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuTransaksiMouseClicked(evt);
            }
        });
        jMenuTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTransaksiActionPerformed(evt);
            }
        });

        jMenuItemPeminjamanBuku.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemPeminjamanBuku.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItemPeminjamanBuku.setText("Peminjaman");
        jMenuItemPeminjamanBuku.setPreferredSize(new java.awt.Dimension(280, 30));
        jMenuItemPeminjamanBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPeminjamanBukuActionPerformed(evt);
            }
        });
        jMenuTransaksi.add(jMenuItemPeminjamanBuku);

        jMenuItemPengembalianBuku.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemPengembalianBuku.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItemPengembalianBuku.setText("Pengembalian");
        jMenuItemPengembalianBuku.setPreferredSize(new java.awt.Dimension(280, 30));
        jMenuItemPengembalianBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPengembalianBukuActionPerformed(evt);
            }
        });
        jMenuTransaksi.add(jMenuItemPengembalianBuku);

        jMenuBar1.add(jMenuTransaksi);

        jMenuLaporan.setBackground(new java.awt.Color(255, 255, 255));
        jMenuLaporan.setForeground(new java.awt.Color(51, 51, 51));
        jMenuLaporan.setText("Laporan");
        jMenuLaporan.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jMenuLaporan.setIconTextGap(20);
        jMenuLaporan.setMargin(new java.awt.Insets(2, 20, 2, 20));
        jMenuLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuLaporanMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuLaporan);

        jMenuLogout.setBackground(new java.awt.Color(255, 255, 255));
        jMenuLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenuLogout.setForeground(new java.awt.Color(51, 51, 51));
        jMenuLogout.setText("Exit");
        jMenuLogout.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jMenuLogout.setIconTextGap(40);
        jMenuLogout.setMargin(new java.awt.Insets(2, 20, 2, 20));
        jMenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLogoutActionPerformed(evt);
            }
        });

        jMenuItemLogout.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemLogout.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.setPreferredSize(new java.awt.Dimension(280, 30));
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenuLogout.add(jMenuItemLogout);

        jMenuBar1.add(jMenuLogout);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textfieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldNamaActionPerformed

    private void textfieldNISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldNISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldNISActionPerformed

    private void textfieldNoTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldNoTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldNoTeleponActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        // TODO add your handling code here
        if( textfieldIDAnggota.getText().equals("") ||
            textfieldNama.getText().equals("") ||
            textfieldNIS.getText().equals("") ||
            textfieldNoTelepon.getText().equals("") ||
            textfieldNamaFileFoto.getText().equals("")
        ){
            javax.swing.JOptionPane. showMessageDialog(null,"Data belum lengkap. \nSilahkan periksa kembali.",
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);            
        }else{
            try {
                String sql = "UPDATE anggota SET nama=?, nis=?, no_tlp=?, foto_anggota=?"
                        + " where id_anggota=?";
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, textfieldNama.getText());            
                stat.setString(2, textfieldNIS.getText());
                stat.setString(3, textfieldNoTelepon.getText());
                stat.setString(4, textfieldNamaFileFoto.getText());
                stat.setString(5, textfieldIDAnggota.getText());

                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil diubah");

                try {
                    String path=new File(".").getCanonicalPath();
                    FileUtils.copyFileToDirectory(file, new File(path+"/foto")); //copy file ke folder image
                } catch (IOException ex) {
                    Logger.getLogger(FormInputBuku.class.getName()).log(Level.SEVERE, null, ex);
                }

                kosong();
                textfieldNama.requestFocus();
                datatable();
                getNextIdAnggota();

            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Diubah "+e);
            }   
        }
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        // TODO add your handling code here:
        if( textfieldIDAnggota.getText().equals("") ||
            textfieldNama.getText().equals("") ||
            textfieldNIS.getText().equals("") ||
            textfieldNoTelepon.getText().equals("") ||
            textfieldNamaFileFoto.getText().equals("")
        ){
            javax.swing.JOptionPane. showMessageDialog(null,"Data belum lengkap. \nSilahkan periksa kembali.",
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);            
        }else{
            String sql = "INSERT INTO anggota VALUES (?,?,?,?,?)";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, textfieldIDAnggota.getText());            
                stat.setString(2, textfieldNama.getText());
                stat.setString(3, textfieldNIS.getText());
                stat.setString(4, textfieldNoTelepon.getText());
                stat.setString(5, textfieldNamaFileFoto.getText());

                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");

                try {
                    String path=new File(".").getCanonicalPath();
                    FileUtils.copyFileToDirectory(file, new File(path+"/foto")); //copy file ke folder image
                } catch (IOException ex) {
                    Logger.getLogger(FormInputBuku.class.getName()).log(Level.SEVERE, null, ex);
                }

                kosong();
                textfieldNama.requestFocus();
                datatable();
                getNextIdAnggota();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan "+e);
            }
        }
    }                                     

    private void ignoreThisMethod(java.awt.event.MouseEvent evt) {                                          
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void tableAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAnggotaMouseClicked
        // TODO add your handling code here:
        int bar = tableAnggota.getSelectedRow();        
        String idAnggota = tabmode.getValueAt(bar, 0).toString();
        String sql = "SELECT * FROM anggota WHERE id_anggota='"+ idAnggota +"'";

       try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("id_anggota");                
                String b = hasil.getString("nama");
                String c = hasil.getString("nis");
                String d = hasil.getString("no_tlp");
                String e = hasil.getString("foto_anggota");
                
                textfieldIDAnggota.setText(a);          
                textfieldNama.setText(b);
                textfieldNIS.setText(c);
                textfieldNoTelepon.setText(d);
                textfieldNamaFileFoto.setText(e);

                try {
                    Toolkit toolkit=Toolkit.getDefaultToolkit();

                    String path=new File(".").getCanonicalPath();

                    Image image=toolkit.getImage(path+"/foto/"+e); //mengambil gambar dari folder foto
                    Image imagedResized=image.getScaledInstance(140, 170, Image.SCALE_DEFAULT); //resize foto sesuai ukuran jlabel
                    ImageIcon icon=new ImageIcon(imagedResized);
                    jLabelGambar.setIcon(icon); // memasang gambar pada jlabel
                }catch (IOException ex) {
                            Logger.getLogger(FormInputBuku.class.getName()).log(Level.SEVERE, null, ex);
                }    
        
            }
       }catch (SQLException e)     {
            JOptionPane.showMessageDialog(null, "Check SQL "+e);

       }   
    
    }//GEN-LAST:event_tableAnggotaMouseClicked

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
                int ok = JOptionPane.showConfirmDialog(null, "Hapus?", "Konfirmasi Dialog",
                JOptionPane.YES_NO_CANCEL_OPTION);
        if(ok == 0){
            String sql = "DELETE FROM anggota WHERE id_anggota='"+textfieldIDAnggota.getText()+"'";
            try{
                PreparedStatement stat =conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil dihapus");
                kosong();
                textfieldNama.requestFocus();
                datatable();
                getNextIdAnggota();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Data gagal dihapus "+e);
            }
       }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_buttonClearActionPerformed

    private void textfieldIDAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldIDAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldIDAnggotaActionPerformed

    private void textfieldCariNamaAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldCariNamaAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldCariNamaAnggotaActionPerformed

    private void buttonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariActionPerformed
        // TODO add your handling code here:
        Object[] Baris = {"Id Anggota", "Nama", "NIS", 
            "No Telepon"};
        tabmode = new DefaultTableModel(null, Baris);
        tableAnggota.setModel(tabmode);
        String sql = "SELECT * FROM anggota WHERE nama like '%"+textfieldCariNamaAnggota.getText()+"%'";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("id_anggota");                
                String b = hasil.getString("nama");
                String c = hasil.getString("nis");
                String d = hasil.getString("no_tlp");
                
                String[] data={a, b, c, d};
                tabmode.addRow(data);
            }
        }catch (SQLException e){
                    
        }        
    }//GEN-LAST:event_buttonCariActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
        datatable();
        textfieldCariNamaAnggota.setText("");
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void textfieldNamaFileFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldNamaFileFotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldNamaFileFotoActionPerformed

    private void jButtonPilihFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPilihFotoActionPerformed
        // TODO add your handling code here:
        jfc = new JFileChooser();
        if(jfc.showOpenDialog(jLabelGambar)==JFileChooser.APPROVE_OPTION){

            Toolkit toolkit=Toolkit.getDefaultToolkit();
            Image image=toolkit.getImage(jfc.getSelectedFile().getAbsolutePath());
            Image imagedResized=image.getScaledInstance(140, 170, Image.SCALE_DEFAULT);
            ImageIcon imageIcon=new ImageIcon(imagedResized);

            jLabelGambar.setIcon(imageIcon);
            textfieldNamaFileFoto.setText(jfc.getSelectedFile().getName());

            file = new File(jfc.getSelectedFile().getPath()); // file untuk dikopi
        }
    }//GEN-LAST:event_jButtonPilihFotoActionPerformed

    private void buttonClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonClear1ActionPerformed

    private void buttonCetakKartuAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCetakKartuAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCetakKartuAnggotaActionPerformed

    private void jMenuLaporan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuLaporan1MouseClicked
        // TODO add your handling code here:
        new FormMenuUtama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuLaporan1MouseClicked

    private void jMenuItemInputDataBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInputDataBukuActionPerformed
        // TODO add your handling code here:
        new FormInputBuku().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemInputDataBukuActionPerformed

    private void jMenuItemRegistrasiAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrasiAnggotaActionPerformed
        // TODO add your handling code here:
        new FormRegistrasi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemRegistrasiAnggotaActionPerformed

    private void jMenuItemRegistrasiPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrasiPetugasActionPerformed
        // TODO add your handling code here:
        new FormPetugas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemRegistrasiPetugasActionPerformed

    private void jMenuItemPeminjamanBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPeminjamanBukuActionPerformed
        // TODO add your handling code here:
        new FormPeminjamanBuku().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemPeminjamanBukuActionPerformed

    private void jMenuItemPengembalianBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPengembalianBukuActionPerformed
        // TODO add your handling code here:
        new FormPengembalianBuku().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemPengembalianBukuActionPerformed

    private void jMenuTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuTransaksiMouseClicked
        // TODO add your handling code here:
        new FormPeminjamanBuku().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuTransaksiMouseClicked

    private void jMenuTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuTransaksiActionPerformed

    private void jMenuLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuLaporanMouseClicked
        // TODO add your handling code here:
        new FormMasterLaporan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuLaporanMouseClicked

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        // TODO add your handling code here:
        new FormLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jMenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLogoutActionPerformed
        // TODO add your handling code here:
        new FormLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRegistrasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonCari;
    private javax.swing.JButton buttonCetakKartuAnggota;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonClear1;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton jButtonPilihFoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelGambar;
    private javax.swing.JLabel jLabelGambar1;
    private javax.swing.JLabel jLabelGambar2;
    private javax.swing.JLabel jLabelGambar3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemInputDataBuku;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemPeminjamanBuku;
    private javax.swing.JMenuItem jMenuItemPengembalianBuku;
    private javax.swing.JMenuItem jMenuItemRegistrasiAnggota;
    private javax.swing.JMenuItem jMenuItemRegistrasiPetugas;
    private javax.swing.JMenu jMenuLaporan;
    private javax.swing.JMenu jMenuLaporan1;
    private javax.swing.JMenu jMenuLogout;
    private javax.swing.JMenu jMenuMaster;
    private javax.swing.JMenu jMenuTransaksi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelPrintAnggota;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelKodeBuku;
    private javax.swing.JLabel labelNIS;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNama1;
    private javax.swing.JLabel labelNama2;
    private javax.swing.JLabel labelNoTelepon;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelTitle1;
    private javax.swing.JLabel labelTitle2;
    private javax.swing.JLabel labelTitle3;
    private javax.swing.JLabel labelTitle4;
    private javax.swing.JLabel labelTitle6;
    private javax.swing.JTable tableAnggota;
    private javax.swing.JTextField textfieldCariNamaAnggota;
    private javax.swing.JTextField textfieldIDAnggota;
    private javax.swing.JTextField textfieldNIS;
    private javax.swing.JTextField textfieldNama;
    private javax.swing.JTextField textfieldNamaFileFoto;
    private javax.swing.JTextField textfieldNoTelepon;
    // End of variables declaration//GEN-END:variables
}
