/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author BrownBox
 */
public class FormRegistrasi extends javax.swing.JFrame {
    
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    /**
     * Creates new form FormRegistrasi
     */
    public FormRegistrasi() {
        initComponents();
        datatable();
    }

        protected void aktif(){
        textfieldIDAnggota.setEnabled(true);
        textfieldNama.setEnabled(true);
        textfieldNIS.setEnabled(true);
        textfieldNoTelepon.setEnabled(true);
        textfieldEmail.setEnabled(true);
        textfieldNama.requestFocus();               
    }
    protected void kosong(){
        textfieldIDAnggota.setText("");
        textfieldNama.setText("");
        textfieldNIS.setText("");
        textfieldNoTelepon.setText("");
        comboboxKelas.setSelectedIndex(0);
        textfieldEmail.setText("");
    }
    protected void datatable(){
        Object[] Baris = {"Id Anggota", "Nama", "NIS", "Kelas", 
            "No Telepon", "Email"};
        tabmode = new DefaultTableModel(null, Baris);
        tableAnggota.setModel(tabmode);
        String sql = "SELECT * FROM anggota";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("id_anggota");                
                String b = hasil.getString("nama");
                String c = hasil.getString("nis");
                String d = hasil.getString("kelas");
                String e = hasil.getString("no_tlp");
                String f = hasil.getString("email");
                
                String[] data={a, b, c, d, e, f};
                tabmode.addRow(data);
            }
        }catch (Exception e){
                    
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        labelTitle1 = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        textfieldNama = new javax.swing.JTextField();
        labelNIS = new javax.swing.JLabel();
        textfieldNIS = new javax.swing.JTextField();
        labelKelas = new javax.swing.JLabel();
        comboboxKelas = new javax.swing.JComboBox<>();
        labelNoTelepon = new javax.swing.JLabel();
        textfieldNoTelepon = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        textfieldEmail = new javax.swing.JTextField();
        buttonSave = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        labelNama1 = new javax.swing.JLabel();
        textfieldIDAnggota = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        buttonCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAnggota = new javax.swing.JTable();
        labelTitle = new javax.swing.JLabel();
        labelNama2 = new javax.swing.JLabel();
        textfieldCariNamaAnggota = new javax.swing.JTextField();
        buttonCancel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrasi Anggota");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitle1.setBackground(new java.awt.Color(71, 127, 255));
        labelTitle1.setFont(new java.awt.Font("Montserrat SemiBold", 1, 24)); // NOI18N
        labelTitle1.setForeground(new java.awt.Color(71, 127, 255));
        labelTitle1.setText("Registrasi Anggota");
        jPanel2.add(labelTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        labelNama.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelNama.setForeground(new java.awt.Color(153, 153, 153));
        labelNama.setText("Nama");
        jPanel2.add(labelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        textfieldNama.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldNama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldNamaActionPerformed(evt);
            }
        });
        jPanel2.add(textfieldNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 230, -1));

        labelNIS.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelNIS.setForeground(new java.awt.Color(153, 153, 153));
        labelNIS.setText("NIS");
        jPanel2.add(labelNIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        textfieldNIS.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldNIS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldNIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldNISActionPerformed(evt);
            }
        });
        jPanel2.add(textfieldNIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 230, -1));

        labelKelas.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelKelas.setForeground(new java.awt.Color(153, 153, 153));
        labelKelas.setText("Kelas");
        jPanel2.add(labelKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        comboboxKelas.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        comboboxKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " X", " XI", " XII" }));
        comboboxKelas.setBorder(null);
        comboboxKelas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(comboboxKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 230, -1));

        labelNoTelepon.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelNoTelepon.setForeground(new java.awt.Color(153, 153, 153));
        labelNoTelepon.setText("No Telepon");
        jPanel2.add(labelNoTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        textfieldNoTelepon.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldNoTelepon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldNoTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldNoTeleponActionPerformed(evt);
            }
        });
        jPanel2.add(textfieldNoTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 230, -1));

        labelEmail.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(153, 153, 153));
        labelEmail.setText("Email");
        jPanel2.add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        textfieldEmail.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldEmailActionPerformed(evt);
            }
        });
        jPanel2.add(textfieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 230, -1));

        buttonSave.setBackground(new java.awt.Color(71, 127, 255));
        buttonSave.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonSave.setForeground(new java.awt.Color(255, 255, 255));
        buttonSave.setText("Save");
        buttonSave.setBorder(null);
        buttonSave.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });
        jPanel2.add(buttonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        buttonEdit.setBackground(new java.awt.Color(71, 127, 255));
        buttonEdit.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonEdit.setForeground(new java.awt.Color(255, 255, 255));
        buttonEdit.setText("Edit");
        buttonEdit.setBorder(null);
        buttonEdit.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });
        jPanel2.add(buttonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 80, -1));

        buttonDelete.setBackground(new java.awt.Color(71, 127, 255));
        buttonDelete.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonDelete.setForeground(new java.awt.Color(255, 255, 255));
        buttonDelete.setText("Delete");
        buttonDelete.setBorder(null);
        buttonDelete.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(buttonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, -1, -1));

        buttonClear.setBackground(new java.awt.Color(71, 127, 255));
        buttonClear.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonClear.setForeground(new java.awt.Color(255, 255, 255));
        buttonClear.setText("Clear");
        buttonClear.setBorder(null);
        buttonClear.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });
        jPanel2.add(buttonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, -1, -1));

        labelNama1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelNama1.setForeground(new java.awt.Color(153, 153, 153));
        labelNama1.setText("ID Anggota");
        jPanel2.add(labelNama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        textfieldIDAnggota.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldIDAnggota.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldIDAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldIDAnggotaActionPerformed(evt);
            }
        });
        jPanel2.add(textfieldIDAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 230, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 420, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonCari.setBackground(new java.awt.Color(71, 127, 255));
        buttonCari.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonCari.setForeground(new java.awt.Color(255, 255, 255));
        buttonCari.setText("Search");
        buttonCari.setBorder(null);
        buttonCari.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        tableAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAnggotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAnggota);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 550, 350));

        labelTitle.setBackground(new java.awt.Color(71, 127, 255));
        labelTitle.setFont(new java.awt.Font("Montserrat SemiBold", 1, 24)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(71, 127, 255));
        labelTitle.setText("Daftar Anggota");
        jPanel1.add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        labelNama2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelNama2.setForeground(new java.awt.Color(153, 153, 153));
        labelNama2.setText("Nama Anggota");
        labelNama2.setPreferredSize(new java.awt.Dimension(84, 30));
        jPanel1.add(labelNama2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 100, 130, -1));

        textfieldCariNamaAnggota.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldCariNamaAnggota.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldCariNamaAnggota.setPreferredSize(new java.awt.Dimension(2, 30));
        textfieldCariNamaAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldCariNamaAnggotaActionPerformed(evt);
            }
        });
        jPanel1.add(textfieldCariNamaAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 210, -1));

        buttonCancel.setBackground(new java.awt.Color(255, 255, 255));
        buttonCancel.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonCancel.setForeground(new java.awt.Color(71, 127, 255));
        buttonCancel.setText("Cancel");
        buttonCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 127, 255)));
        buttonCancel.setContentAreaFilled(false);
        buttonCancel.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 590, 600));

        jPanel3.setBackground(new java.awt.Color(212, 210, 212));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/images/cancel.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel3.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, -1));

        jLabel1.setBackground(new java.awt.Color(212, 210, 212));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/images/bar.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textfieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldNamaActionPerformed

    private void textfieldNISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldNISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldNISActionPerformed

    private void textfieldNoTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldNoTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldNoTeleponActionPerformed

    private void textfieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldEmailActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        // TODO add your handling code here
        try {
            String sql = "UPDATE anggota SET nama=?, nis=?, kelas=?, no_tlp=?, email=? where id_anggota=?";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, textfieldNama.getText());            
            stat.setString(2, textfieldNIS.getText());
            stat.setString(3, comboboxKelas.getSelectedItem().toString());
            stat.setString(4, textfieldNoTelepon.getText());
            stat.setString(5, textfieldEmail.getText());
            stat.setString(6, textfieldIDAnggota.getText());
            

            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            kosong();
            textfieldIDAnggota.requestFocus();
            datatable();
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah "+e);
        }        
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO anggota VALUES (?,?,?,?,?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, textfieldIDAnggota.getText());            
            stat.setString(2, textfieldNama.getText());
            stat.setString(3, textfieldNIS.getText());
            stat.setString(4, comboboxKelas.getSelectedItem().toString());
            stat.setString(5, textfieldNoTelepon.getText());
            stat.setString(6, textfieldEmail.getText());

            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            kosong();
            textfieldIDAnggota.requestFocus();
            datatable();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan "+e);
        }
    }                                     

    private void ignoreThisMethod(java.awt.event.MouseEvent evt) {                                          
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void tableAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAnggotaMouseClicked
        // TODO add your handling code here:
        int bar = tableAnggota.getSelectedRow();        
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();        
        
        textfieldIDAnggota.setText(a);
        textfieldNama.setText(b);
        textfieldNIS.setText(c);
        comboboxKelas.setSelectedItem(d);
        textfieldNoTelepon.setText(e);
        textfieldEmail.setText(f);
    }//GEN-LAST:event_tableAnggotaMouseClicked

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
                int ok = JOptionPane.showConfirmDialog(null, "Hapus?", "Konfirmasi Dialog",
                JOptionPane.YES_NO_CANCEL_OPTION);
        if(ok == 0){
            String sql = "DELETE FROM anggota WHERE id_anggota='"+textfieldIDAnggota.getText()+"'";
            try{
                PreparedStatement stat =conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil dihapus");
                kosong();
                textfieldIDAnggota.requestFocus();
                datatable();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Data gagal dihapus "+e);
            }
       }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_buttonClearActionPerformed

    private void textfieldIDAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldIDAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldIDAnggotaActionPerformed

    private void textfieldCariNamaAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldCariNamaAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldCariNamaAnggotaActionPerformed

    private void buttonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariActionPerformed
        // TODO add your handling code here:
        Object[] Baris = {"Id Anggota", "Nama", "NIS", "Kelas", 
            "No Telepon", "Email"};
        tabmode = new DefaultTableModel(null, Baris);
        tableAnggota.setModel(tabmode);
        String sql = "SELECT * FROM anggota WHERE nama like '%"+textfieldCariNamaAnggota.getText()+"%'";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("id_anggota");                
                String b = hasil.getString("nama");
                String c = hasil.getString("nis");
                String d = hasil.getString("kelas");
                String e = hasil.getString("no_tlp");
                String f = hasil.getString("email");
                
                String[] data={a, b, c, d, e, f};
                tabmode.addRow(data);
            }
        }catch (Exception e){
                    
        }        
    }//GEN-LAST:event_buttonCariActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
        datatable();
        textfieldCariNamaAnggota.setText("");
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        new FormMenuUtama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRegistrasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonCari;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonSave;
    private javax.swing.JComboBox<String> comboboxKelas;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelKelas;
    private javax.swing.JLabel labelNIS;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNama1;
    private javax.swing.JLabel labelNama2;
    private javax.swing.JLabel labelNoTelepon;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelTitle1;
    private javax.swing.JTable tableAnggota;
    private javax.swing.JTextField textfieldCariNamaAnggota;
    private javax.swing.JTextField textfieldEmail;
    private javax.swing.JTextField textfieldIDAnggota;
    private javax.swing.JTextField textfieldNIS;
    private javax.swing.JTextField textfieldNama;
    private javax.swing.JTextField textfieldNoTelepon;
    // End of variables declaration//GEN-END:variables
}
