/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.sql.*;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author BrownBox
 */
public final class FormPetugas extends javax.swing.JFrame {
    
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    
    /**
     * Creates new form FormRegistrasi
     */
    public FormPetugas() {
        initComponents();
        datatable();
    }
    

    protected void aktif(){
        textfieldNamaPetugas.setEnabled(true);
        textfieldUsernamePetugas.setEnabled(true);
        textfieldNamaPetugas.requestFocus();    
        buttonDelete.setEnabled(false);
    }
    protected void kosong(){
        textfieldNamaPetugas.setText("");
        textfieldUsernamePetugas.setText("");
        textfieldPasswordPetugas.setText("");
    }
    
    protected void datatable(){
        Object[] Baris = {"Nama", "Username", "Password"};
        tabmode = new DefaultTableModel(null, Baris);
        tableAnggota.setModel(tabmode);
        String sql = "SELECT * FROM petugas";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("nama_petugas");                
                String b = hasil.getString("username");
                String c = hasil.getString("password");
                
                String[] data={a, b, c};
                tabmode.addRow(data);
            }
        }catch (Exception e){
            System.out.print("Cek kembali datatable");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        labelTitle1 = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        textfieldNamaPetugas = new javax.swing.JTextField();
        labelNIS = new javax.swing.JLabel();
        textfieldUsernamePetugas = new javax.swing.JTextField();
        buttonSave = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        labelNIS1 = new javax.swing.JLabel();
        textfieldPasswordPetugas = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        buttonCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAnggota = new javax.swing.JTable();
        labelTitle = new javax.swing.JLabel();
        labelNama2 = new javax.swing.JLabel();
        textfieldCariNamaPetugas = new javax.swing.JTextField();
        buttonCancel = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuLaporan1 = new javax.swing.JMenu();
        jMenuMaster = new javax.swing.JMenu();
        jMenuItemInputDataBuku = new javax.swing.JMenuItem();
        jMenuItemRegistrasiAnggota = new javax.swing.JMenuItem();
        jMenuItemRegistrasiPetugas = new javax.swing.JMenuItem();
        jMenuTransaksi = new javax.swing.JMenu();
        jMenuItemPeminjamanBuku = new javax.swing.JMenuItem();
        jMenuItemPengembalianBuku = new javax.swing.JMenuItem();
        jMenuLaporan = new javax.swing.JMenu();
        jMenuLogout = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrasi Anggota");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitle1.setBackground(new java.awt.Color(9, 110, 59));
        labelTitle1.setFont(new java.awt.Font("Montserrat SemiBold", 1, 24)); // NOI18N
        labelTitle1.setForeground(new java.awt.Color(9, 110, 59));
        labelTitle1.setText("Registrasi Petugas");
        jPanel2.add(labelTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        labelNama.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelNama.setForeground(new java.awt.Color(153, 153, 153));
        labelNama.setText("Nama");
        jPanel2.add(labelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        textfieldNamaPetugas.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldNamaPetugas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldNamaPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldNamaPetugasActionPerformed(evt);
            }
        });
        jPanel2.add(textfieldNamaPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 230, -1));

        labelNIS.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelNIS.setForeground(new java.awt.Color(153, 153, 153));
        labelNIS.setText("Username");
        jPanel2.add(labelNIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        textfieldUsernamePetugas.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldUsernamePetugas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldUsernamePetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldUsernamePetugasActionPerformed(evt);
            }
        });
        jPanel2.add(textfieldUsernamePetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 230, -1));

        buttonSave.setBackground(new java.awt.Color(9, 110, 59));
        buttonSave.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonSave.setForeground(new java.awt.Color(255, 255, 255));
        buttonSave.setText("Simpan");
        buttonSave.setBorder(null);
        buttonSave.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });
        jPanel2.add(buttonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        buttonEdit.setBackground(new java.awt.Color(9, 110, 59));
        buttonEdit.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonEdit.setForeground(new java.awt.Color(255, 255, 255));
        buttonEdit.setText("Ubah");
        buttonEdit.setBorder(null);
        buttonEdit.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });
        jPanel2.add(buttonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 80, -1));

        buttonDelete.setBackground(new java.awt.Color(9, 110, 59));
        buttonDelete.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonDelete.setForeground(new java.awt.Color(255, 255, 255));
        buttonDelete.setText("Hapus");
        buttonDelete.setBorder(null);
        buttonDelete.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(buttonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        buttonClear.setBackground(new java.awt.Color(9, 110, 59));
        buttonClear.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonClear.setForeground(new java.awt.Color(255, 255, 255));
        buttonClear.setText("Bersihkan");
        buttonClear.setBorder(null);
        buttonClear.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });
        jPanel2.add(buttonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 80, -1));

        labelNIS1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelNIS1.setForeground(new java.awt.Color(153, 153, 153));
        labelNIS1.setText("Password");
        jPanel2.add(labelNIS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        textfieldPasswordPetugas.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldPasswordPetugas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldPasswordPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldPasswordPetugasActionPerformed(evt);
            }
        });
        jPanel2.add(textfieldPasswordPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 230, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonCari.setBackground(new java.awt.Color(9, 110, 59));
        buttonCari.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonCari.setForeground(new java.awt.Color(255, 255, 255));
        buttonCari.setText("Cari");
        buttonCari.setBorder(null);
        buttonCari.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        tableAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAnggotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAnggota);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 550, 350));

        labelTitle.setBackground(new java.awt.Color(9, 110, 59));
        labelTitle.setFont(new java.awt.Font("Montserrat SemiBold", 1, 24)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(9, 110, 59));
        labelTitle.setText("Daftar Petugas");
        jPanel1.add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        labelNama2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelNama2.setForeground(new java.awt.Color(153, 153, 153));
        labelNama2.setText("Nama Petugas");
        labelNama2.setPreferredSize(new java.awt.Dimension(84, 30));
        jPanel1.add(labelNama2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 100, 130, -1));

        textfieldCariNamaPetugas.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldCariNamaPetugas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldCariNamaPetugas.setPreferredSize(new java.awt.Dimension(2, 30));
        textfieldCariNamaPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldCariNamaPetugasActionPerformed(evt);
            }
        });
        jPanel1.add(textfieldCariNamaPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 210, -1));

        buttonCancel.setBackground(new java.awt.Color(9, 110, 59));
        buttonCancel.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonCancel.setForeground(new java.awt.Color(9, 110, 59));
        buttonCancel.setText("Batal");
        buttonCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(9, 110, 59)));
        buttonCancel.setContentAreaFilled(false);
        buttonCancel.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 590, 600));

        jMenuBar1.setBackground(new java.awt.Color(245, 247, 250));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(76, 40));

        jMenuLaporan1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuLaporan1.setForeground(new java.awt.Color(51, 51, 51));
        jMenuLaporan1.setText("Menu Utama");
        jMenuLaporan1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jMenuLaporan1.setIconTextGap(20);
        jMenuLaporan1.setMargin(new java.awt.Insets(2, 20, 2, 20));
        jMenuLaporan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuLaporan1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuLaporan1);

        jMenuMaster.setBackground(new java.awt.Color(255, 255, 255));
        jMenuMaster.setForeground(new java.awt.Color(51, 51, 51));
        jMenuMaster.setText("Master");
        jMenuMaster.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jMenuMaster.setIconTextGap(20);
        jMenuMaster.setMargin(new java.awt.Insets(2, 20, 2, 20));

        jMenuItemInputDataBuku.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemInputDataBuku.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItemInputDataBuku.setText("Input Data Buku");
        jMenuItemInputDataBuku.setPreferredSize(new java.awt.Dimension(280, 30));
        jMenuItemInputDataBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInputDataBukuActionPerformed(evt);
            }
        });
        jMenuMaster.add(jMenuItemInputDataBuku);

        jMenuItemRegistrasiAnggota.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemRegistrasiAnggota.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItemRegistrasiAnggota.setText("Registrasi Anggota");
        jMenuItemRegistrasiAnggota.setPreferredSize(new java.awt.Dimension(280, 30));
        jMenuItemRegistrasiAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrasiAnggotaActionPerformed(evt);
            }
        });
        jMenuMaster.add(jMenuItemRegistrasiAnggota);

        jMenuItemRegistrasiPetugas.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemRegistrasiPetugas.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItemRegistrasiPetugas.setText("Registrasi Petugas");
        jMenuItemRegistrasiPetugas.setPreferredSize(new java.awt.Dimension(280, 30));
        jMenuItemRegistrasiPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrasiPetugasActionPerformed(evt);
            }
        });
        jMenuMaster.add(jMenuItemRegistrasiPetugas);

        jMenuBar1.add(jMenuMaster);

        jMenuTransaksi.setBackground(new java.awt.Color(255, 255, 255));
        jMenuTransaksi.setForeground(new java.awt.Color(51, 51, 51));
        jMenuTransaksi.setText("Transaksi");
        jMenuTransaksi.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jMenuTransaksi.setIconTextGap(20);
        jMenuTransaksi.setMargin(new java.awt.Insets(2, 20, 2, 20));
        jMenuTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuTransaksiMouseClicked(evt);
            }
        });
        jMenuTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTransaksiActionPerformed(evt);
            }
        });

        jMenuItemPeminjamanBuku.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemPeminjamanBuku.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItemPeminjamanBuku.setText("Peminjaman");
        jMenuItemPeminjamanBuku.setPreferredSize(new java.awt.Dimension(280, 30));
        jMenuItemPeminjamanBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPeminjamanBukuActionPerformed(evt);
            }
        });
        jMenuTransaksi.add(jMenuItemPeminjamanBuku);

        jMenuItemPengembalianBuku.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemPengembalianBuku.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItemPengembalianBuku.setText("Pengembalian");
        jMenuItemPengembalianBuku.setPreferredSize(new java.awt.Dimension(280, 30));
        jMenuItemPengembalianBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPengembalianBukuActionPerformed(evt);
            }
        });
        jMenuTransaksi.add(jMenuItemPengembalianBuku);

        jMenuBar1.add(jMenuTransaksi);

        jMenuLaporan.setBackground(new java.awt.Color(255, 255, 255));
        jMenuLaporan.setForeground(new java.awt.Color(51, 51, 51));
        jMenuLaporan.setText("Laporan");
        jMenuLaporan.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jMenuLaporan.setIconTextGap(20);
        jMenuLaporan.setMargin(new java.awt.Insets(2, 20, 2, 20));
        jMenuLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuLaporanMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuLaporan);

        jMenuLogout.setBackground(new java.awt.Color(255, 255, 255));
        jMenuLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenuLogout.setForeground(new java.awt.Color(51, 51, 51));
        jMenuLogout.setText("Exit");
        jMenuLogout.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jMenuLogout.setIconTextGap(40);
        jMenuLogout.setMargin(new java.awt.Insets(2, 20, 2, 20));
        jMenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLogoutActionPerformed(evt);
            }
        });

        jMenuItemLogout.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemLogout.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.setPreferredSize(new java.awt.Dimension(280, 30));
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenuLogout.add(jMenuItemLogout);

        jMenuBar1.add(jMenuLogout);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textfieldNamaPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldNamaPetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldNamaPetugasActionPerformed

    private void textfieldUsernamePetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldUsernamePetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldUsernamePetugasActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        // TODO add your handling code here
        if(  textfieldNamaPetugas.getText().equals("") ||       
             textfieldPasswordPetugas.getText().equals("") ||
             textfieldUsernamePetugas.getText().equals("")
        ){
            javax.swing.JOptionPane. showMessageDialog(null,"Data belum lengkap. \nSilahkan periksa kembali.",
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);              
        }else{
            try {
                String sql = "UPDATE petugas SET nama_petugas=?, password=? where username=?";
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, textfieldNamaPetugas.getText());            
                stat.setString(2, textfieldPasswordPetugas.getText());
                stat.setString(3, textfieldUsernamePetugas.getText());


                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil diubah");
                kosong();
                textfieldNamaPetugas.requestFocus();
                datatable();

            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Diubah "+e);
            }    
        }
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        // TODO add your handling code here:
        String nama = textfieldNamaPetugas.getText();
        String username = textfieldUsernamePetugas.getText();
        String password = textfieldPasswordPetugas.getText();
        
        if(  nama.equals("") ||       
             password.equals("") ||
             username.equals("")
        ){
            javax.swing.JOptionPane. showMessageDialog(null,"Data belum lengkap. \nSilahkan periksa kembali.",
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);              
        }else{
            try{                
                //Cek username tidak boleh sama
                String sqlCheck = "SELECT username FROM petugas WHERE username='"+ username +"'";
                java.sql.Statement stat = conn.createStatement();
                ResultSet hasil = stat.executeQuery(sqlCheck);

                if(hasil.next()){
                    JOptionPane.showMessageDialog(null, "Username sudah terdaftar!");
                }else{
                   String sql = "INSERT INTO petugas VALUES (?,?,?)";
                    try{
                        PreparedStatement stat2 = conn.prepareStatement(sql);
                        stat2.setString(1, textfieldNamaPetugas.getText());            
                        stat2.setString(2, textfieldUsernamePetugas.getText());
                        stat2.setString(3, password);

                        stat2.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                        kosong();
                        textfieldNamaPetugas.requestFocus();
                        datatable();
                    }catch(SQLException e){
                        JOptionPane.showMessageDialog(null, "Data Gagal Disimpan "+e);
                    }
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }                                     

    private void ignoreThisMethod(java.awt.event.MouseEvent evt) {                                          
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void tableAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAnggotaMouseClicked
        // TODO add your handling code here:
        int bar = tableAnggota.getSelectedRow();        
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
   
        
        textfieldNamaPetugas.setText(a);
        textfieldUsernamePetugas.setText(b);
        textfieldPasswordPetugas.setText(c);
        buttonSave.setEnabled(false);
        buttonDelete.setEnabled(true);
        textfieldUsernamePetugas.setEnabled(false);       
    }//GEN-LAST:event_tableAnggotaMouseClicked

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
                int ok = JOptionPane.showConfirmDialog(null, "Hapus?", "Konfirmasi Dialog",
                JOptionPane.YES_NO_CANCEL_OPTION);
        if(ok == 0){
            String sql = "DELETE FROM petugas WHERE username='"+textfieldUsernamePetugas.getText()+"'";
            try{
                PreparedStatement stat =conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil dihapus");
                kosong();
                textfieldNamaPetugas.requestFocus();
                datatable();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Data gagal dihapus "+e);
            }
       }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        // TODO add your handling code here:
        kosong();
        buttonSave.setEnabled(true);
        textfieldUsernamePetugas.setEnabled(true);  
        buttonDelete.setEnabled(false);
    }//GEN-LAST:event_buttonClearActionPerformed

    private void textfieldCariNamaPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldCariNamaPetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldCariNamaPetugasActionPerformed

    private void buttonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariActionPerformed
        // TODO add your handling code here:
        Object[] Baris = {"Nama", "Username", "Password"};
        tabmode = new DefaultTableModel(null, Baris);
        tableAnggota.setModel(tabmode);
        String sql = "SELECT * FROM petugas";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("nama_petugas");                
                String b = hasil.getString("username");
                String c = hasil.getString("password");
                
                String[] data={a, b, c};
                tabmode.addRow(data);
            }
        }catch (Exception e){
                    
        }
    }//GEN-LAST:event_buttonCariActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
        datatable();
        textfieldCariNamaPetugas.setText("");
        buttonSave.setEnabled(true);

    }//GEN-LAST:event_buttonCancelActionPerformed

    private void textfieldPasswordPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldPasswordPetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldPasswordPetugasActionPerformed

    private void jMenuLaporan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuLaporan1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuLaporan1MouseClicked

    private void jMenuItemInputDataBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInputDataBukuActionPerformed
        // TODO add your handling code here:
        new FormInputBuku().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemInputDataBukuActionPerformed

    private void jMenuItemRegistrasiAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrasiAnggotaActionPerformed
        // TODO add your handling code here:
        new FormRegistrasi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemRegistrasiAnggotaActionPerformed

    private void jMenuItemRegistrasiPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrasiPetugasActionPerformed
        // TODO add your handling code here:
        new FormPetugas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemRegistrasiPetugasActionPerformed

    private void jMenuItemPeminjamanBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPeminjamanBukuActionPerformed
        // TODO add your handling code here:
        new FormPeminjamanBuku().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemPeminjamanBukuActionPerformed

    private void jMenuItemPengembalianBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPengembalianBukuActionPerformed
        // TODO add your handling code here:
        new FormPengembalianBuku().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemPengembalianBukuActionPerformed

    private void jMenuTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuTransaksiMouseClicked
        // TODO add your handling code here:
        new FormPeminjamanBuku().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuTransaksiMouseClicked

    private void jMenuTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuTransaksiActionPerformed

    private void jMenuLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuLaporanMouseClicked
        // TODO add your handling code here:
        new FormMasterLaporan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuLaporanMouseClicked

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        // TODO add your handling code here:
        new FormLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jMenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLogoutActionPerformed
        // TODO add your handling code here:
        new FormLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPetugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonCari;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonSave;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemInputDataBuku;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemPeminjamanBuku;
    private javax.swing.JMenuItem jMenuItemPengembalianBuku;
    private javax.swing.JMenuItem jMenuItemRegistrasiAnggota;
    private javax.swing.JMenuItem jMenuItemRegistrasiPetugas;
    private javax.swing.JMenu jMenuLaporan;
    private javax.swing.JMenu jMenuLaporan1;
    private javax.swing.JMenu jMenuLogout;
    private javax.swing.JMenu jMenuMaster;
    private javax.swing.JMenu jMenuTransaksi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNIS;
    private javax.swing.JLabel labelNIS1;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNama2;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelTitle1;
    private javax.swing.JTable tableAnggota;
    private javax.swing.JTextField textfieldCariNamaPetugas;
    private javax.swing.JTextField textfieldNamaPetugas;
    private javax.swing.JTextField textfieldPasswordPetugas;
    private javax.swing.JTextField textfieldUsernamePetugas;
    // End of variables declaration//GEN-END:variables
}
