/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author BrownBox
 */
public class FormInputBuku extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;

    /**
     * Creates new form FormRegistrasi
     */
    public FormInputBuku() {
        initComponents();
        datatable();
    }
        
    protected void aktif(){
        textfieldKodeBuku.setEnabled(true);
        textfieldJudul.setEnabled(true);
        textfieldPengarang.setEnabled(true);
        textfieldPenerbit.setEnabled(true);
        textfieldTahunTerbit.setEnabled(true);
        textfieldEdisi.setEnabled(true);
        textfieldISBN.setEnabled(true);
        textfieldJumlah.setEnabled(true);
        textfieldKodeBuku.requestFocus();               
    }
    protected void kosong(){
        comboboxKategoriBuku.setSelectedIndex(0);
        textfieldKodeBuku.setText("");
        textfieldJudul.setText("");
        textfieldPengarang.setText("");
        textfieldPenerbit.setText("");
        textfieldTahunTerbit.setText("");
        textfieldEdisi.setText("");
        textfieldISBN.setText("");
        textfieldJumlah.setText("");
    }
    protected void datatable(){
        Object[] Baris = {"Kategori", "Kode Buku", "Judul", "Pengarang", 
            "Penerbit", "Tahun Terbit", "Edisi", "ISBN", "Jumlah"};
        tabmode = new DefaultTableModel(null, Baris);
        tableBuku.setModel(tabmode);
        String sql = "SELECT * FROM buku";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("kategori_buku");
                String b = hasil.getString("kode_buku");
                String c = hasil.getString("judul_buku");
                String d = hasil.getString("pengarang");
                String e = hasil.getString("penerbit");
                String f = hasil.getString("tahun_terbit");
                String g = hasil.getString("edisi");
                String h = hasil.getString("isbn");
                String i = hasil.getString("jumlah");
                String[] data={a, b, c, d, e, f, g, h, i};
                tabmode.addRow(data);
            }
        }catch (Exception e){                  
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        labelKategoriBuku = new javax.swing.JLabel();
        comboboxKategoriBuku = new javax.swing.JComboBox<>();
        labelKodeBuku = new javax.swing.JLabel();
        textfieldKodeBuku = new javax.swing.JTextField();
        labelJudul = new javax.swing.JLabel();
        textfieldJudul = new javax.swing.JTextField();
        labelPengarang = new javax.swing.JLabel();
        textfieldPengarang = new javax.swing.JTextField();
        labelPenerbit = new javax.swing.JLabel();
        textfieldPenerbit = new javax.swing.JTextField();
        labelTahunTerbit = new javax.swing.JLabel();
        textfieldTahunTerbit = new javax.swing.JTextField();
        labelEdisi = new javax.swing.JLabel();
        textfieldEdisi = new javax.swing.JTextField();
        labelISBN = new javax.swing.JLabel();
        textfieldISBN = new javax.swing.JTextField();
        labelJumlah = new javax.swing.JLabel();
        textfieldJumlah = new javax.swing.JTextField();
        buttonSave = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        labelTitle2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBuku = new javax.swing.JTable();
        labelTitle3 = new javax.swing.JLabel();
        labelNama2 = new javax.swing.JLabel();
        textfieldCariJudulBuku = new javax.swing.JTextField();
        buttonCari = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Input Data Buku");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelKategoriBuku.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelKategoriBuku.setForeground(new java.awt.Color(153, 153, 153));
        labelKategoriBuku.setText("Kategori Buku");
        jPanel2.add(labelKategoriBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        comboboxKategoriBuku.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        comboboxKategoriBuku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Umum", " Agama", " Sosial", " Teknologi", " Bahasa", " Sains & Matematika", " Seni", " Sejarah", " Sastra" }));
        comboboxKategoriBuku.setBorder(null);
        jPanel2.add(comboboxKategoriBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 230, -1));

        labelKodeBuku.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelKodeBuku.setForeground(new java.awt.Color(153, 153, 153));
        labelKodeBuku.setText("Kode Buku");
        jPanel2.add(labelKodeBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        textfieldKodeBuku.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldKodeBuku.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldKodeBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldKodeBukuActionPerformed(evt);
            }
        });
        jPanel2.add(textfieldKodeBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 230, -1));

        labelJudul.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelJudul.setForeground(new java.awt.Color(153, 153, 153));
        labelJudul.setText("Judul");
        jPanel2.add(labelJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        textfieldJudul.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldJudul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldJudulActionPerformed(evt);
            }
        });
        jPanel2.add(textfieldJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 230, -1));

        labelPengarang.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelPengarang.setForeground(new java.awt.Color(153, 153, 153));
        labelPengarang.setText("Pengarang");
        jPanel2.add(labelPengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        textfieldPengarang.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldPengarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldPengarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldPengarangActionPerformed(evt);
            }
        });
        jPanel2.add(textfieldPengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 230, -1));

        labelPenerbit.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelPenerbit.setForeground(new java.awt.Color(153, 153, 153));
        labelPenerbit.setText("Penerbit");
        jPanel2.add(labelPenerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        textfieldPenerbit.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldPenerbit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldPenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldPenerbitActionPerformed(evt);
            }
        });
        jPanel2.add(textfieldPenerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 230, -1));

        labelTahunTerbit.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelTahunTerbit.setForeground(new java.awt.Color(153, 153, 153));
        labelTahunTerbit.setText("Tahun Terbit");
        jPanel2.add(labelTahunTerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        textfieldTahunTerbit.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldTahunTerbit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldTahunTerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldTahunTerbitActionPerformed(evt);
            }
        });
        jPanel2.add(textfieldTahunTerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 230, -1));

        labelEdisi.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelEdisi.setForeground(new java.awt.Color(153, 153, 153));
        labelEdisi.setText("Edisi");
        jPanel2.add(labelEdisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        textfieldEdisi.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldEdisi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldEdisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldEdisiActionPerformed(evt);
            }
        });
        jPanel2.add(textfieldEdisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 230, -1));

        labelISBN.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelISBN.setForeground(new java.awt.Color(153, 153, 153));
        labelISBN.setText("ISBN");
        jPanel2.add(labelISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        textfieldISBN.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldISBN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldISBNActionPerformed(evt);
            }
        });
        jPanel2.add(textfieldISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 230, -1));

        labelJumlah.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelJumlah.setForeground(new java.awt.Color(153, 153, 153));
        labelJumlah.setText("Jumlah");
        jPanel2.add(labelJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        textfieldJumlah.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldJumlah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldJumlahActionPerformed(evt);
            }
        });
        jPanel2.add(textfieldJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 230, -1));

        buttonSave.setBackground(new java.awt.Color(71, 127, 255));
        buttonSave.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonSave.setForeground(new java.awt.Color(255, 255, 255));
        buttonSave.setText("Save");
        buttonSave.setBorder(null);
        buttonSave.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });
        jPanel2.add(buttonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        buttonEdit.setBackground(new java.awt.Color(71, 127, 255));
        buttonEdit.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonEdit.setForeground(new java.awt.Color(255, 255, 255));
        buttonEdit.setText("Edit");
        buttonEdit.setBorder(null);
        buttonEdit.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });
        jPanel2.add(buttonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 80, -1));

        buttonDelete.setBackground(new java.awt.Color(71, 127, 255));
        buttonDelete.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonDelete.setForeground(new java.awt.Color(255, 255, 255));
        buttonDelete.setText("Delete");
        buttonDelete.setBorder(null);
        buttonDelete.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(buttonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, -1, -1));

        buttonClear.setBackground(new java.awt.Color(71, 127, 255));
        buttonClear.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonClear.setForeground(new java.awt.Color(255, 255, 255));
        buttonClear.setText("Clear");
        buttonClear.setBorder(null);
        buttonClear.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });
        jPanel2.add(buttonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, -1, -1));

        labelTitle2.setBackground(new java.awt.Color(71, 127, 255));
        labelTitle2.setFont(new java.awt.Font("Montserrat SemiBold", 1, 24)); // NOI18N
        labelTitle2.setForeground(new java.awt.Color(71, 127, 255));
        labelTitle2.setText("Input Data Buku");
        jPanel2.add(labelTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 420, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBuku);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 143, 540, 380));

        labelTitle3.setFont(new java.awt.Font("Montserrat SemiBold", 1, 24)); // NOI18N
        labelTitle3.setForeground(new java.awt.Color(71, 127, 255));
        labelTitle3.setText("Daftar Buku");
        jPanel1.add(labelTitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        labelNama2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelNama2.setForeground(new java.awt.Color(153, 153, 153));
        labelNama2.setText("Judul Buku");
        labelNama2.setPreferredSize(new java.awt.Dimension(84, 30));
        jPanel1.add(labelNama2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 100, 130, -1));

        textfieldCariJudulBuku.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldCariJudulBuku.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldCariJudulBuku.setPreferredSize(new java.awt.Dimension(2, 30));
        textfieldCariJudulBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldCariJudulBukuActionPerformed(evt);
            }
        });
        jPanel1.add(textfieldCariJudulBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 210, -1));

        buttonCari.setBackground(new java.awt.Color(71, 127, 255));
        buttonCari.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonCari.setForeground(new java.awt.Color(255, 255, 255));
        buttonCari.setText("Search");
        buttonCari.setBorder(null);
        buttonCari.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        buttonCancel.setBackground(new java.awt.Color(255, 255, 255));
        buttonCancel.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonCancel.setForeground(new java.awt.Color(71, 127, 255));
        buttonCancel.setText("Cancel");
        buttonCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 127, 255)));
        buttonCancel.setContentAreaFilled(false);
        buttonCancel.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 580, 600));

        jPanel3.setBackground(new java.awt.Color(212, 210, 212));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/images/cancel.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, -1));

        jLabel1.setBackground(new java.awt.Color(212, 210, 212));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/images/bar.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textfieldKodeBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldKodeBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldKodeBukuActionPerformed

    private void textfieldJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldJudulActionPerformed

    private void textfieldPengarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldPengarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldPengarangActionPerformed

    private void textfieldPenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldPenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldPenerbitActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        // TODO add your handling code here
        try {
            String sql = "UPDATE buku SET kategori_buku=?, judul_buku=?, pengarang=?, "
                    + "penerbit=?, tahun_terbit=?, edisi=?, isbn=?, jumlah=? where kode_buku=?";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, comboboxKategoriBuku.getSelectedItem().toString());
            stat.setString(2, textfieldJudul.getText());
            stat.setString(3, textfieldPengarang.getText());
            stat.setString(4, textfieldPenerbit.getText());
            stat.setString(5, textfieldTahunTerbit.getText());
            stat.setString(6, textfieldEdisi.getText());
            stat.setString(7, textfieldISBN.getText());
            stat.setString(8, textfieldJumlah.getText());
            stat.setString(9, textfieldKodeBuku.getText());
                    
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            kosong();
            textfieldKodeBuku.requestFocus();
            datatable();
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah "+e);
        }        
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO buku VALUES (?,?,?,?,?,?,?,?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, comboboxKategoriBuku.getSelectedItem().toString());
            stat.setString(2, textfieldKodeBuku.getText());
            stat.setString(3, textfieldJudul.getText());            
            stat.setString(4, textfieldPengarang.getText());
            stat.setString(5, textfieldPenerbit.getText());
            stat.setString(6, textfieldTahunTerbit.getText());
            stat.setString(7, textfieldEdisi.getText());
            stat.setString(8, textfieldISBN.getText());
            stat.setString(9, textfieldJumlah.getText());

            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            kosong();
            textfieldKodeBuku.requestFocus();
            datatable();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan "+e);
        }
    }                                     

    private void ignoreThisMethod(java.awt.event.MouseEvent evt) {                                          
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
                int ok = JOptionPane.showConfirmDialog(null, "Hapus?", "Konfirmasi Dialog",
                JOptionPane.YES_NO_CANCEL_OPTION);
        if(ok == 0){
            String sql = "DELETE FROM buku WHERE kode_buku='"+textfieldKodeBuku.getText()+"'";
            try{
                PreparedStatement stat =conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil dihapus");
                kosong();
                textfieldKodeBuku.requestFocus();
                datatable();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Data gagal dihapus "+e);
            }
       }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_buttonClearActionPerformed

    private void textfieldEdisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldEdisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldEdisiActionPerformed

    private void textfieldISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldISBNActionPerformed

    private void textfieldJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldJumlahActionPerformed

    private void textfieldTahunTerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldTahunTerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldTahunTerbitActionPerformed

    private void tableBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBukuMouseClicked
        // TODO add your handling code here:
        int bar = tableBuku.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        String g = tabmode.getValueAt(bar, 6).toString();
        String h = tabmode.getValueAt(bar, 7).toString();
        String i = tabmode.getValueAt(bar, 8).toString();

        comboboxKategoriBuku.setSelectedItem(a);
        textfieldKodeBuku.setText(b);
        textfieldJudul.setText(c);
        textfieldPengarang.setText(d);
        textfieldPenerbit.setText(e);
        textfieldTahunTerbit.setText(f);
        textfieldEdisi.setText(g);
        textfieldISBN.setText(h);
        textfieldJumlah.setText(i);
    }//GEN-LAST:event_tableBukuMouseClicked

    private void textfieldCariJudulBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldCariJudulBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldCariJudulBukuActionPerformed

    private void buttonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariActionPerformed
        // TODO add your handling code here:
        Object[] Baris = {"Kategori", "Kode Buku", "Judul", "Pengarang", 
            "Penerbit", "Tahun Terbit", "Edisi", "ISBN", "Jumlah"};
        tabmode = new DefaultTableModel(null, Baris);
        tableBuku.setModel(tabmode);
        String sql = "SELECT * FROM buku WHERE judul_buku like '%"+textfieldCariJudulBuku.getText()+"%'";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("kategori_buku");
                String b = hasil.getString("kode_buku");
                String c = hasil.getString("judul_buku");
                String d = hasil.getString("pengarang");
                String e = hasil.getString("penerbit");
                String f = hasil.getString("tahun_terbit");
                String g = hasil.getString("edisi");
                String h = hasil.getString("isbn");
                String i = hasil.getString("jumlah");
                String[] data={a, b, c, d, e, f, g, h, i};
                tabmode.addRow(data);
            }
        }catch (Exception e){

        }
    }//GEN-LAST:event_buttonCariActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
        datatable();
        textfieldCariJudulBuku.setText("");
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        new FormMenuUtama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInputBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInputBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInputBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInputBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormInputBuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonCari;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonSave;
    private javax.swing.JComboBox<String> comboboxKategoriBuku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelEdisi;
    private javax.swing.JLabel labelISBN;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelJumlah;
    private javax.swing.JLabel labelKategoriBuku;
    private javax.swing.JLabel labelKodeBuku;
    private javax.swing.JLabel labelNama2;
    private javax.swing.JLabel labelPenerbit;
    private javax.swing.JLabel labelPengarang;
    private javax.swing.JLabel labelTahunTerbit;
    private javax.swing.JLabel labelTitle2;
    private javax.swing.JLabel labelTitle3;
    private javax.swing.JTable tableBuku;
    private javax.swing.JTextField textfieldCariJudulBuku;
    private javax.swing.JTextField textfieldEdisi;
    private javax.swing.JTextField textfieldISBN;
    private javax.swing.JTextField textfieldJudul;
    private javax.swing.JTextField textfieldJumlah;
    private javax.swing.JTextField textfieldKodeBuku;
    private javax.swing.JTextField textfieldPenerbit;
    private javax.swing.JTextField textfieldPengarang;
    private javax.swing.JTextField textfieldTahunTerbit;
    // End of variables declaration//GEN-END:variables
}
