/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author BrownBox
 */
public class FormPencarianBuku extends javax.swing.JFrame {
    private final Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
       

    /**
     * Creates new form FormRegistrasi
     */
    public FormPencarianBuku() {
        initComponents();
        kosong();
        datatable();
//        textFieldKategoriBuku.setOpaque(true);
    }
        
    protected void kosong(){
        textFieldKategoriBuku.setText("");
        textfieldJudul.setText("");
        textfieldPengarang.setText("");
        textfieldPenerbit.setText("");
        textfieldTahunTerbit.setText("");
        textfieldKodeRak.setText("");
        textfieldJumlah.setText("");
    }
    protected void datatable(){
        Object[] Baris = {"Kode Buku", "Judul", "Pengarang", 
            "Penerbit", "Jumlah"};
        tabmode = new DefaultTableModel(null, Baris);
        tableBuku.setModel(tabmode);
        String sql = "SELECT kode_buku, judul_buku, pengarang, penerbit, "
                + "jumlah FROM buku";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("kode_buku");
                String b = hasil.getString("judul_buku");
                String c = hasil.getString("pengarang");
                String d = hasil.getString("penerbit");
                String e = hasil.getString("jumlah");

                String[] data={a, b, c, d, e};
                tabmode.addRow(data);

            }
        }catch (SQLException e){                  
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        labelJumlah = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textfieldJudul = new javax.swing.JLabel();
        textfieldPengarang = new javax.swing.JLabel();
        textfieldPenerbit = new javax.swing.JLabel();
        labelJumlah1 = new javax.swing.JLabel();
        textFieldKategoriBuku = new javax.swing.JLabel();
        textfieldTahunTerbit = new javax.swing.JLabel();
        textfieldKodeRak = new javax.swing.JLabel();
        textfieldJumlah = new javax.swing.JLabel();
        jLabelGambar = new javax.swing.JLabel();
        textfieldNamaFileBuku = new javax.swing.JLabel();
        labelTahunTerbit1 = new javax.swing.JLabel();
        textfieldKodeBuku = new javax.swing.JLabel();
        labelTahunTerbit2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBuku = new javax.swing.JTable();
        textfieldCariJudulBuku = new javax.swing.JTextField();
        buttonCari = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Input Data Buku");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 228, 229));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelJumlah.setFont(new java.awt.Font("Balsamiq Sans", 0, 12)); // NOI18N
        labelJumlah.setForeground(new java.awt.Color(102, 102, 102));
        labelJumlah.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelJumlah.setText("Jumlah");
        jPanel2.add(labelJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 120, 25));

        jLabel3.setBackground(new java.awt.Color(71, 127, 255));
        jLabel3.setFont(new java.awt.Font("Balsamiq Sans", 1, 21)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(246, 93, 78));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Detail Buku");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        textfieldJudul.setFont(new java.awt.Font("Balsamiq Sans", 1, 24)); // NOI18N
        textfieldJudul.setForeground(new java.awt.Color(51, 51, 51));
        textfieldJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textfieldJudul.setText("Judul");
        jPanel2.add(textfieldJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 320, -1));

        textfieldPengarang.setFont(new java.awt.Font("Balsamiq Sans", 0, 14)); // NOI18N
        textfieldPengarang.setForeground(new java.awt.Color(51, 51, 51));
        textfieldPengarang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textfieldPengarang.setText("Pengarang");
        jPanel2.add(textfieldPengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 320, -1));

        textfieldPenerbit.setFont(new java.awt.Font("Balsamiq Sans", 0, 18)); // NOI18N
        textfieldPenerbit.setForeground(new java.awt.Color(51, 51, 51));
        textfieldPenerbit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textfieldPenerbit.setText("Penerbit");
        jPanel2.add(textfieldPenerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 120, -1));

        labelJumlah1.setFont(new java.awt.Font("Balsamiq Sans", 0, 12)); // NOI18N
        labelJumlah1.setForeground(new java.awt.Color(102, 102, 102));
        labelJumlah1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelJumlah1.setText("Kode Rak");
        jPanel2.add(labelJumlah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 120, 25));

        textFieldKategoriBuku.setBackground(new java.awt.Color(204, 204, 204));
        textFieldKategoriBuku.setFont(new java.awt.Font("Balsamiq Sans", 1, 12)); // NOI18N
        textFieldKategoriBuku.setForeground(new java.awt.Color(153, 153, 153));
        textFieldKategoriBuku.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textFieldKategoriBuku.setText("Kategori");
        jPanel2.add(textFieldKategoriBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 140, 30));

        textfieldTahunTerbit.setFont(new java.awt.Font("Balsamiq Sans", 0, 18)); // NOI18N
        textfieldTahunTerbit.setForeground(new java.awt.Color(51, 51, 51));
        textfieldTahunTerbit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textfieldTahunTerbit.setText("Tahun Terbit");
        jPanel2.add(textfieldTahunTerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 120, -1));

        textfieldKodeRak.setFont(new java.awt.Font("Balsamiq Sans", 0, 18)); // NOI18N
        textfieldKodeRak.setForeground(new java.awt.Color(51, 51, 51));
        textfieldKodeRak.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textfieldKodeRak.setText("Kode Rak");
        jPanel2.add(textfieldKodeRak, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 120, -1));

        textfieldJumlah.setFont(new java.awt.Font("Balsamiq Sans", 0, 18)); // NOI18N
        textfieldJumlah.setForeground(new java.awt.Color(51, 51, 51));
        textfieldJumlah.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textfieldJumlah.setText("Jumlah");
        jPanel2.add(textfieldJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 120, -1));

        jLabelGambar.setOpaque(true);
        jPanel2.add(jLabelGambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 140, 170));

        textfieldNamaFileBuku.setText("NamaFileBuku");
        jPanel2.add(textfieldNamaFileBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        labelTahunTerbit1.setFont(new java.awt.Font("Balsamiq Sans", 0, 12)); // NOI18N
        labelTahunTerbit1.setForeground(new java.awt.Color(102, 102, 102));
        labelTahunTerbit1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTahunTerbit1.setText("Tahun Terbit");
        jPanel2.add(labelTahunTerbit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 120, 25));

        textfieldKodeBuku.setFont(new java.awt.Font("Balsamiq Sans", 0, 12)); // NOI18N
        textfieldKodeBuku.setForeground(new java.awt.Color(246, 93, 78));
        textfieldKodeBuku.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textfieldKodeBuku.setText("Tahun Terbit");
        jPanel2.add(textfieldKodeBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 150, -1));

        labelTahunTerbit2.setFont(new java.awt.Font("Balsamiq Sans", 0, 12)); // NOI18N
        labelTahunTerbit2.setForeground(new java.awt.Color(102, 102, 102));
        labelTahunTerbit2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTahunTerbit2.setText("Penerbit");
        labelTahunTerbit2.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel2.add(labelTahunTerbit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 120, 25));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 420, 600));

        jPanel1.setBackground(new java.awt.Color(246, 93, 78));
        jPanel1.setForeground(new java.awt.Color(246, 93, 78));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableBuku.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBuku);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 540, 190));

        textfieldCariJudulBuku.setFont(new java.awt.Font("Balsamiq Sans", 1, 18)); // NOI18N
        textfieldCariJudulBuku.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textfieldCariJudulBuku.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldCariJudulBuku.setPreferredSize(new java.awt.Dimension(2, 30));
        textfieldCariJudulBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldCariJudulBukuActionPerformed(evt);
            }
        });
        jPanel1.add(textfieldCariJudulBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 450, -1));

        buttonCari.setBackground(new java.awt.Color(9, 110, 59));
        buttonCari.setFont(new java.awt.Font("Balsamiq Sans", 1, 18)); // NOI18N
        buttonCari.setForeground(new java.awt.Color(255, 255, 255));
        buttonCari.setText("Cari");
        buttonCari.setBorder(null);
        buttonCari.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 70, 30));

        jLabel6.setBackground(new java.awt.Color(71, 127, 255));
        jLabel6.setFont(new java.awt.Font("Balsamiq Sans", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Masukkan Judul Buku Yang Kamu Cari!");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jLabel4.setBackground(new java.awt.Color(71, 127, 255));
        jLabel4.setFont(new java.awt.Font("Balsamiq Sans", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PENCARIAN BUKU");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBukuMouseClicked
        // TODO add your handling code here:

        int bar = tableBuku.getSelectedRow();
        String kode_buku = tabmode.getValueAt(bar, 0).toString();

        String sql = "SELECT * FROM buku WHERE kode_buku='"+ kode_buku +"'";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("kategori_buku");
                String b = hasil.getString("kode_buku");
                String c = hasil.getString("judul_buku");
                String d = hasil.getString("pengarang");
                String e = hasil.getString("penerbit");
                String f = hasil.getString("tahun_terbit");
                String g = hasil.getString("kode_rak");
                String h = hasil.getString("jumlah");
                String i = hasil.getString("image");
                 
                textFieldKategoriBuku.setText(a);
                textfieldKodeBuku.setText(b);
                textfieldJudul.setText(c);
                textfieldPengarang.setText(d);
                textfieldPenerbit.setText(e);
                textfieldTahunTerbit.setText(f);
                textfieldKodeRak.setText(g);
                textfieldJumlah.setText(h);
                textfieldNamaFileBuku.setText(i);   
      
                //Untuk Ambil Gambar dari folder Image yang namanya ada di database
                try {
                    Toolkit toolkit=Toolkit.getDefaultToolkit();

                    String path=new File(".").getCanonicalPath();

                    Image image=toolkit.getImage(path+"/image/"+i); //mengambil gambar dari folder image
                    Image imagedResized=image.getScaledInstance(140, 170, Image.SCALE_DEFAULT); //resize foto sesuai ukuran jlabel
                    ImageIcon icon=new ImageIcon(imagedResized);
                    jLabelGambar.setIcon(icon); // memasang gambar pada jlabel
                }catch (IOException ex) {
                            Logger.getLogger(FormInputBuku.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }catch (SQLException e)     {
            
        }        
        
    }//GEN-LAST:event_tableBukuMouseClicked

    private void textfieldCariJudulBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldCariJudulBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldCariJudulBukuActionPerformed

    private void buttonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariActionPerformed
        // TODO add your handling code here:
        Object[] Baris = {"Kode Buku", "Judul", "Pengarang", 
            "Penerbit", "Jumlah"};
        tabmode = new DefaultTableModel(null, Baris);
        tableBuku.setModel(tabmode);
        String sql = "SELECT * FROM buku WHERE judul_buku like '%"+textfieldCariJudulBuku.getText()+"%'";

        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("kode_buku");
                String b = hasil.getString("judul_buku");
                String c = hasil.getString("pengarang");
                String d = hasil.getString("penerbit");
                String e = hasil.getString("jumlah");

                String[] data={a, b, c, d, e};
                tabmode.addRow(data);

            }
        }catch (SQLException e){                  
        }
    }//GEN-LAST:event_buttonCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPencarianBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPencarianBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPencarianBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPencarianBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPencarianBuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCari;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelGambar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelJumlah;
    private javax.swing.JLabel labelJumlah1;
    private javax.swing.JLabel labelTahunTerbit1;
    private javax.swing.JLabel labelTahunTerbit2;
    private javax.swing.JTable tableBuku;
    private javax.swing.JLabel textFieldKategoriBuku;
    private javax.swing.JTextField textfieldCariJudulBuku;
    private javax.swing.JLabel textfieldJudul;
    private javax.swing.JLabel textfieldJumlah;
    private javax.swing.JLabel textfieldKodeBuku;
    private javax.swing.JLabel textfieldKodeRak;
    private javax.swing.JLabel textfieldNamaFileBuku;
    private javax.swing.JLabel textfieldPenerbit;
    private javax.swing.JLabel textfieldPengarang;
    private javax.swing.JLabel textfieldTahunTerbit;
    // End of variables declaration//GEN-END:variables
}
