/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author BrownBox
 */
public final class FormMenuUtama extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;    

    /**
     * Creates new form FormMenuUtama
     */
    public FormMenuUtama() {
        initComponents();
        countBuku();
        countAnggota();
        countTransaksi();
    }
    
    protected void countBuku(){
        String sql = "SELECT COUNT(*) FROM buku";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String jumlahBuku = hasil.getString("COUNT(*)");
                labelJumlahBuku.setText(" "+jumlahBuku);
            }
        }catch (Exception e){

        }        
    }
    protected void countAnggota(){
        String sql = "SELECT COUNT(*) FROM anggota";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String jumlahAnggota = hasil.getString("COUNT(*)");
                labelJumlahAnggota.setText(" "+jumlahAnggota);
            }
        }catch (Exception e){

        }        
    }
    protected void countTransaksi(){
        String sql = "SELECT COUNT(*) FROM transaksi";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String jumlahTransaksi = hasil.getString("COUNT(*)");
                labelJumlahTransaksi.setText(" "+jumlahTransaksi);
            }
        }catch (Exception e){

        }        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        data_buku = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        data_anggota = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        data_transaksi = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        data_laporan = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        panel_data_transaksi = new javax.swing.JPanel();
        labelJumlahTransaksi = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        panel_data_buku = new javax.swing.JPanel();
        labelJumlahBuku = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        panel_data_anggota = new javax.swing.JPanel();
        labelJumlahAnggota = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuMaster = new javax.swing.JMenu();
        jMenuItemInputDataBuku = new javax.swing.JMenuItem();
        jMenuItemRegistrasiAnggota = new javax.swing.JMenuItem();
        jMenuTransaksi = new javax.swing.JMenu();
        jMenuLaporan = new javax.swing.JMenu();
        jMenuLogout = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menu Utama");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1000, 630));
        setPreferredSize(new java.awt.Dimension(1000, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 247, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        data_buku.setBackground(new java.awt.Color(76, 207, 233));
        data_buku.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(76, 207, 233), 1, true));
        data_buku.setPreferredSize(new java.awt.Dimension(200, 200));
        data_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                data_bukuMouseClicked(evt);
            }
        });
        data_buku.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/images/bookshelf.png"))); // NOI18N
        data_buku.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jLabel4.setBackground(new java.awt.Color(71, 127, 255));
        jLabel4.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data Buku");
        data_buku.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        jLabel16.setBackground(new java.awt.Color(71, 127, 255));
        jLabel16.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Input");
        data_buku.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        jPanel1.add(data_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 230, 180));

        data_anggota.setBackground(new java.awt.Color(238, 182, 43));
        data_anggota.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(238, 182, 43), 1, true));
        data_anggota.setPreferredSize(new java.awt.Dimension(200, 200));
        data_anggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                data_anggotaMouseClicked(evt);
            }
        });
        data_anggota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/images/membership.png"))); // NOI18N
        data_anggota.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel11.setBackground(new java.awt.Color(71, 127, 255));
        jLabel11.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Registrasi Anggota");
        data_anggota.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jPanel1.add(data_anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 230, 180));

        data_transaksi.setBackground(new java.awt.Color(152, 197, 44));
        data_transaksi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(152, 197, 44), 1, true));
        data_transaksi.setPreferredSize(new java.awt.Dimension(200, 200));
        data_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                data_transaksiMouseClicked(evt);
            }
        });
        data_transaksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/images/book.png"))); // NOI18N
        data_transaksi.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel7.setBackground(new java.awt.Color(71, 127, 255));
        jLabel7.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Peminjaman Buku");
        data_transaksi.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/images/reload.png"))); // NOI18N
        data_transaksi.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel9.setBackground(new java.awt.Color(71, 127, 255));
        jLabel9.setFont(new java.awt.Font("Montserrat SemiBold", 0, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Transaksi ");
        data_transaksi.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        jPanel1.add(data_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 470, 170));

        data_laporan.setBackground(new java.awt.Color(198, 95, 225));
        data_laporan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(198, 95, 225), 1, true));
        data_laporan.setPreferredSize(new java.awt.Dimension(200, 200));
        data_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                data_laporanMouseClicked(evt);
            }
        });
        data_laporan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/images/report.png"))); // NOI18N
        data_laporan.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel13.setBackground(new java.awt.Color(71, 127, 255));
        jLabel13.setFont(new java.awt.Font("Montserrat SemiBold", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Laporan");
        data_laporan.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jPanel1.add(data_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 200, 360));

        panel_data_transaksi.setBackground(new java.awt.Color(255, 255, 255));
        panel_data_transaksi.setPreferredSize(new java.awt.Dimension(200, 200));
        panel_data_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_data_transaksiMouseClicked(evt);
            }
        });
        panel_data_transaksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelJumlahTransaksi.setBackground(new java.awt.Color(71, 127, 255));
        labelJumlahTransaksi.setFont(new java.awt.Font("Segoe UI Semibold", 0, 68)); // NOI18N
        labelJumlahTransaksi.setForeground(new java.awt.Color(102, 102, 102));
        labelJumlahTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJumlahTransaksi.setText("00");
        panel_data_transaksi.add(labelJumlahTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 110));

        jLabel22.setBackground(new java.awt.Color(71, 127, 255));
        jLabel22.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 153, 153));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Transaksi");
        panel_data_transaksi.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 200, -1));

        jPanel1.add(panel_data_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, 150));

        panel_data_buku.setBackground(new java.awt.Color(255, 255, 255));
        panel_data_buku.setPreferredSize(new java.awt.Dimension(200, 200));
        panel_data_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_data_bukuMouseClicked(evt);
            }
        });
        panel_data_buku.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelJumlahBuku.setBackground(new java.awt.Color(71, 127, 255));
        labelJumlahBuku.setFont(new java.awt.Font("Segoe UI Semibold", 0, 68)); // NOI18N
        labelJumlahBuku.setForeground(new java.awt.Color(102, 102, 102));
        labelJumlahBuku.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJumlahBuku.setText("00");
        panel_data_buku.add(labelJumlahBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 110));

        jLabel19.setBackground(new java.awt.Color(71, 127, 255));
        jLabel19.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 153, 153));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Pustaka");
        panel_data_buku.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 250, -1));

        jPanel1.add(panel_data_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 250, 150));

        panel_data_anggota.setBackground(new java.awt.Color(255, 255, 255));
        panel_data_anggota.setPreferredSize(new java.awt.Dimension(200, 200));
        panel_data_anggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_data_anggotaMouseClicked(evt);
            }
        });
        panel_data_anggota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelJumlahAnggota.setBackground(new java.awt.Color(71, 127, 255));
        labelJumlahAnggota.setFont(new java.awt.Font("Segoe UI Semibold", 0, 68)); // NOI18N
        labelJumlahAnggota.setForeground(new java.awt.Color(102, 102, 102));
        labelJumlahAnggota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJumlahAnggota.setText("00");
        panel_data_anggota.add(labelJumlahAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 110));

        jLabel17.setBackground(new java.awt.Color(71, 127, 255));
        jLabel17.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Anggota");
        panel_data_anggota.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 240, -1));

        jPanel1.add(panel_data_anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 240, 150));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 560));

        jMenuBar1.setBackground(new java.awt.Color(245, 247, 250));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(76, 40));

        jMenuMaster.setBackground(new java.awt.Color(255, 255, 255));
        jMenuMaster.setForeground(new java.awt.Color(51, 51, 51));
        jMenuMaster.setText("Master");
        jMenuMaster.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jMenuMaster.setIconTextGap(20);
        jMenuMaster.setMargin(new java.awt.Insets(2, 20, 2, 20));

        jMenuItemInputDataBuku.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemInputDataBuku.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItemInputDataBuku.setText("Input Data Buku");
        jMenuItemInputDataBuku.setPreferredSize(new java.awt.Dimension(280, 30));
        jMenuItemInputDataBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInputDataBukuActionPerformed(evt);
            }
        });
        jMenuMaster.add(jMenuItemInputDataBuku);

        jMenuItemRegistrasiAnggota.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemRegistrasiAnggota.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItemRegistrasiAnggota.setText("Registrasi Anggota");
        jMenuItemRegistrasiAnggota.setPreferredSize(new java.awt.Dimension(280, 30));
        jMenuItemRegistrasiAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrasiAnggotaActionPerformed(evt);
            }
        });
        jMenuMaster.add(jMenuItemRegistrasiAnggota);

        jMenuBar1.add(jMenuMaster);

        jMenuTransaksi.setBackground(new java.awt.Color(255, 255, 255));
        jMenuTransaksi.setForeground(new java.awt.Color(51, 51, 51));
        jMenuTransaksi.setText("Transaksi");
        jMenuTransaksi.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jMenuTransaksi.setIconTextGap(20);
        jMenuTransaksi.setMargin(new java.awt.Insets(2, 20, 2, 20));
        jMenuTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuTransaksiMouseClicked(evt);
            }
        });
        jMenuTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTransaksiActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuTransaksi);

        jMenuLaporan.setBackground(new java.awt.Color(255, 255, 255));
        jMenuLaporan.setForeground(new java.awt.Color(51, 51, 51));
        jMenuLaporan.setText("Laporan");
        jMenuLaporan.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jMenuLaporan.setIconTextGap(20);
        jMenuLaporan.setMargin(new java.awt.Insets(2, 20, 2, 20));
        jMenuLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuLaporanMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuLaporan);

        jMenuLogout.setBackground(new java.awt.Color(255, 255, 255));
        jMenuLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenuLogout.setForeground(new java.awt.Color(51, 51, 51));
        jMenuLogout.setText("Exit");
        jMenuLogout.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jMenuLogout.setIconTextGap(40);
        jMenuLogout.setMargin(new java.awt.Insets(2, 20, 2, 20));
        jMenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLogoutActionPerformed(evt);
            }
        });

        jMenuItemLogout.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemLogout.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.setPreferredSize(new java.awt.Dimension(280, 30));
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenuLogout.add(jMenuItemLogout);

        jMenuBar1.add(jMenuLogout);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemRegistrasiAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrasiAnggotaActionPerformed
        // TODO add your handling code here:
        new FormRegistrasi().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jMenuItemRegistrasiAnggotaActionPerformed

    private void jMenuItemInputDataBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInputDataBukuActionPerformed
        // TODO add your handling code here:
        new FormInputBuku().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jMenuItemInputDataBukuActionPerformed

    private void jMenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLogoutActionPerformed
        // TODO add your handling code here:
        new FormLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuLogoutActionPerformed

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        // TODO add your handling code here:
        new FormLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void panel_data_anggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_data_anggotaMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_panel_data_anggotaMouseClicked

    private void data_anggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_anggotaMouseClicked
        // TODO add your handling code here:
        new FormRegistrasi().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_data_anggotaMouseClicked

    private void data_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_transaksiMouseClicked
        // TODO add your handling code here:
        new FormTransaksi().setVisible(true);
                this.dispose();

    }//GEN-LAST:event_data_transaksiMouseClicked

    private void jMenuTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuTransaksiActionPerformed

    private void jMenuTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuTransaksiMouseClicked
        // TODO add your handling code here:
        new FormTransaksi().setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_jMenuTransaksiMouseClicked

    private void jMenuLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuLaporanMouseClicked
        // TODO add your handling code here:
        new FormMasterLaporan().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jMenuLaporanMouseClicked

    private void data_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_bukuMouseClicked
        // TODO add your handling code here:
        new FormInputBuku().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_data_bukuMouseClicked

    private void panel_data_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_data_bukuMouseClicked
        // TODO add your handling code here:
        new FormInputBuku().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panel_data_bukuMouseClicked

    private void panel_data_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_data_transaksiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_data_transaksiMouseClicked

    private void data_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_laporanMouseClicked
        // TODO add your handling code here:
        new FormMasterLaporan().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_data_laporanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel data_anggota;
    private javax.swing.JPanel data_buku;
    private javax.swing.JPanel data_laporan;
    private javax.swing.JPanel data_transaksi;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemInputDataBuku;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemRegistrasiAnggota;
    private javax.swing.JMenu jMenuLaporan;
    private javax.swing.JMenu jMenuLogout;
    private javax.swing.JMenu jMenuMaster;
    private javax.swing.JMenu jMenuTransaksi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelJumlahAnggota;
    private javax.swing.JLabel labelJumlahBuku;
    private javax.swing.JLabel labelJumlahTransaksi;
    private javax.swing.JPanel panel_data_anggota;
    private javax.swing.JPanel panel_data_buku;
    private javax.swing.JPanel panel_data_transaksi;
    // End of variables declaration//GEN-END:variables
}
