/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import org.apache.commons.io.FileUtils;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

/**
 *
 * @author BrownBox
 */
public class FormInputBuku extends javax.swing.JFrame {
    private final Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    File file;
    JFileChooser jfc;

    /**
     * Creates new form FormRegistrasi
     */
   
    public FormInputBuku() {
        initComponents();
        datatable();
        textfieldKodeBuku.setDocument(new JTextFieldLimit(10) );
    }
  
    class JTextFieldLimit extends PlainDocument {
        private int limit;
        JTextFieldLimit(int limit) {
          super();
          this.limit = limit;
        }

        JTextFieldLimit(int limit, boolean upper) {
          super();
          this.limit = limit;
        }

        public void insertString(int offset, String str, AttributeSet attr) throws BadLocationException {
          if (str == null)
            return;

          if ((getLength() + str.length()) <= limit) {
            super.insertString(offset, str, attr);
          }
        }
    }
    
    protected void aktif(){
        textfieldKodeBuku.setEnabled(true);
        textfieldJudul.setEnabled(true);
        textfieldPengarang.setEnabled(true);
        textfieldPenerbit.setEnabled(true);
        textfieldTahunTerbit.setEnabled(true);
        textfieldKodeRak.setEnabled(true);
        textfieldJumlah.setEnabled(true);
        textfieldKodeBuku.requestFocus();               
    }
    protected void kosong(){
        comboboxKategoriBuku.setSelectedIndex(0);
        textfieldKodeBuku.setText("");
        textfieldJudul.setText("");
        textfieldPengarang.setText("");
        textfieldPenerbit.setText("");
        textfieldTahunTerbit.setText("");
        textfieldKodeRak.setText("");
        textfieldJumlah.setText("");
        textfieldNamaFileBuku.setText("");
        jLabelGambar.setIcon(null); 
    }
    protected void datatable(){
        Object[] Baris = {"Kode Buku", "Judul", "Pengarang", 
            "Penerbit", "Jumlah"};
        tabmode = new DefaultTableModel(null, Baris);
        tableBuku.setModel(tabmode);
        String sql = "SELECT kode_buku, judul_buku, pengarang, penerbit, "
                + "jumlah FROM buku";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("kode_buku");
                String b = hasil.getString("judul_buku");
                String c = hasil.getString("pengarang");
                String d = hasil.getString("penerbit");
                String e = hasil.getString("jumlah");

                String[] data={a, b, c, d, e};
                tabmode.addRow(data);

            }
        }catch (SQLException e){                  
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        labelKategoriBuku = new javax.swing.JLabel();
        comboboxKategoriBuku = new javax.swing.JComboBox<>();
        labelKodeBuku = new javax.swing.JLabel();
        textfieldKodeBuku = new javax.swing.JTextField();
        labelJudul = new javax.swing.JLabel();
        textfieldJudul = new javax.swing.JTextField();
        labelPengarang = new javax.swing.JLabel();
        textfieldPengarang = new javax.swing.JTextField();
        labelPenerbit = new javax.swing.JLabel();
        textfieldPenerbit = new javax.swing.JTextField();
        labelTahunTerbit = new javax.swing.JLabel();
        textfieldTahunTerbit = new javax.swing.JTextField();
        labelEdisi = new javax.swing.JLabel();
        textfieldKodeRak = new javax.swing.JTextField();
        labelJumlah = new javax.swing.JLabel();
        textfieldJumlah = new javax.swing.JTextField();
        buttonSave = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        labelTitle2 = new javax.swing.JLabel();
        labelKodeBuku1 = new javax.swing.JLabel();
        jButtonPilihGambar = new javax.swing.JButton();
        jLabelGambar = new javax.swing.JLabel();
        textfieldNamaFileBuku = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBuku = new javax.swing.JTable();
        labelTitle3 = new javax.swing.JLabel();
        labelNama2 = new javax.swing.JLabel();
        textfieldCariJudulBuku = new javax.swing.JTextField();
        buttonCari = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuMaster = new javax.swing.JMenu();
        jMenuItemInputDataBuku = new javax.swing.JMenuItem();
        jMenuItemRegistrasiAnggota = new javax.swing.JMenuItem();
        jMenuItemRegistrasiPetugas = new javax.swing.JMenuItem();
        jMenuTransaksi = new javax.swing.JMenu();
        jMenuItemPeminjamanBuku = new javax.swing.JMenuItem();
        jMenuItemPengembalianBuku = new javax.swing.JMenuItem();
        jMenuLaporan = new javax.swing.JMenu();
        jMenuLogout = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Input Data Buku");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelKategoriBuku.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelKategoriBuku.setForeground(new java.awt.Color(153, 153, 153));
        labelKategoriBuku.setText("Kategori Buku");
        jPanel2.add(labelKategoriBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        comboboxKategoriBuku.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        comboboxKategoriBuku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Umum", " Agama", " Sosial", " Teknologi", " Bahasa", " Sains & Matematika", " Seni", " Sejarah", " Sastra" }));
        comboboxKategoriBuku.setBorder(null);
        jPanel2.add(comboboxKategoriBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 170, -1));

        labelKodeBuku.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelKodeBuku.setForeground(new java.awt.Color(153, 153, 153));
        labelKodeBuku.setText("Gambar");
        jPanel2.add(labelKodeBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        textfieldKodeBuku.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldKodeBuku.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldKodeBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldKodeBukuActionPerformed(evt);
            }
        });
        jPanel2.add(textfieldKodeBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 170, -1));

        labelJudul.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelJudul.setForeground(new java.awt.Color(153, 153, 153));
        labelJudul.setText("Judul");
        jPanel2.add(labelJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        textfieldJudul.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldJudul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldJudulActionPerformed(evt);
            }
        });
        jPanel2.add(textfieldJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 170, -1));

        labelPengarang.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelPengarang.setForeground(new java.awt.Color(153, 153, 153));
        labelPengarang.setText("Pengarang");
        jPanel2.add(labelPengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        textfieldPengarang.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldPengarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldPengarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldPengarangActionPerformed(evt);
            }
        });
        jPanel2.add(textfieldPengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 170, -1));

        labelPenerbit.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelPenerbit.setForeground(new java.awt.Color(153, 153, 153));
        labelPenerbit.setText("Penerbit");
        jPanel2.add(labelPenerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        textfieldPenerbit.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldPenerbit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldPenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldPenerbitActionPerformed(evt);
            }
        });
        jPanel2.add(textfieldPenerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 170, -1));

        labelTahunTerbit.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelTahunTerbit.setForeground(new java.awt.Color(153, 153, 153));
        labelTahunTerbit.setText("Tahun Terbit");
        jPanel2.add(labelTahunTerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        textfieldTahunTerbit.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldTahunTerbit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldTahunTerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldTahunTerbitActionPerformed(evt);
            }
        });
        jPanel2.add(textfieldTahunTerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 170, -1));

        labelEdisi.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelEdisi.setForeground(new java.awt.Color(153, 153, 153));
        labelEdisi.setText("Kode Rak");
        jPanel2.add(labelEdisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        textfieldKodeRak.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldKodeRak.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldKodeRak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldKodeRakActionPerformed(evt);
            }
        });
        jPanel2.add(textfieldKodeRak, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 170, -1));

        labelJumlah.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelJumlah.setForeground(new java.awt.Color(153, 153, 153));
        labelJumlah.setText("Jumlah");
        jPanel2.add(labelJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        textfieldJumlah.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldJumlah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldJumlahActionPerformed(evt);
            }
        });
        jPanel2.add(textfieldJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 170, -1));

        buttonSave.setBackground(new java.awt.Color(9, 110, 59));
        buttonSave.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonSave.setForeground(new java.awt.Color(255, 255, 255));
        buttonSave.setText("Simpan");
        buttonSave.setBorder(null);
        buttonSave.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });
        jPanel2.add(buttonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));

        buttonEdit.setBackground(new java.awt.Color(9, 110, 59));
        buttonEdit.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonEdit.setForeground(new java.awt.Color(255, 255, 255));
        buttonEdit.setText("Ubah");
        buttonEdit.setBorder(null);
        buttonEdit.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });
        jPanel2.add(buttonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 80, -1));

        buttonDelete.setBackground(new java.awt.Color(9, 110, 59));
        buttonDelete.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonDelete.setForeground(new java.awt.Color(255, 255, 255));
        buttonDelete.setText("Hapus");
        buttonDelete.setBorder(null);
        buttonDelete.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(buttonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, -1, -1));

        buttonClear.setBackground(new java.awt.Color(9, 110, 59));
        buttonClear.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonClear.setForeground(new java.awt.Color(255, 255, 255));
        buttonClear.setText("Bersihkan");
        buttonClear.setBorder(null);
        buttonClear.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });
        jPanel2.add(buttonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 80, -1));

        labelTitle2.setBackground(new java.awt.Color(71, 127, 255));
        labelTitle2.setFont(new java.awt.Font("Montserrat SemiBold", 1, 24)); // NOI18N
        labelTitle2.setForeground(new java.awt.Color(9, 110, 59));
        labelTitle2.setText("Input Data Buku");
        jPanel2.add(labelTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        labelKodeBuku1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelKodeBuku1.setForeground(new java.awt.Color(153, 153, 153));
        labelKodeBuku1.setText("Kode Buku");
        jPanel2.add(labelKodeBuku1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jButtonPilihGambar.setBackground(new java.awt.Color(9, 110, 59));
        jButtonPilihGambar.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jButtonPilihGambar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPilihGambar.setText("Pilih Gambar");
        jButtonPilihGambar.setBorder(null);
        jButtonPilihGambar.setPreferredSize(new java.awt.Dimension(75, 30));
        jButtonPilihGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPilihGambarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonPilihGambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 110, -1));

        jLabelGambar.setOpaque(true);
        jPanel2.add(jLabelGambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 140, 170));

        textfieldNamaFileBuku.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldNamaFileBuku.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldNamaFileBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldNamaFileBukuActionPerformed(evt);
            }
        });
        jPanel2.add(textfieldNamaFileBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 140, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 570));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBuku);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 143, 450, 380));

        labelTitle3.setFont(new java.awt.Font("Montserrat SemiBold", 1, 24)); // NOI18N
        labelTitle3.setForeground(new java.awt.Color(9, 110, 59));
        labelTitle3.setText("Daftar Buku");
        jPanel1.add(labelTitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        labelNama2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelNama2.setForeground(new java.awt.Color(153, 153, 153));
        labelNama2.setText("Masukan Judul Buku");
        labelNama2.setPreferredSize(new java.awt.Dimension(84, 30));
        jPanel1.add(labelNama2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 280, -1));

        textfieldCariJudulBuku.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldCariJudulBuku.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldCariJudulBuku.setPreferredSize(new java.awt.Dimension(2, 30));
        textfieldCariJudulBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldCariJudulBukuActionPerformed(evt);
            }
        });
        jPanel1.add(textfieldCariJudulBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 280, -1));

        buttonCari.setBackground(new java.awt.Color(9, 110, 59));
        buttonCari.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonCari.setForeground(new java.awt.Color(255, 255, 255));
        buttonCari.setText("Cari");
        buttonCari.setBorder(null);
        buttonCari.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        buttonCancel.setBackground(new java.awt.Color(9, 110, 59));
        buttonCancel.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonCancel.setForeground(new java.awt.Color(9, 110, 59));
        buttonCancel.setText("Batal");
        buttonCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 127, 255)));
        buttonCancel.setContentAreaFilled(false);
        buttonCancel.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 500, 570));

        jMenuBar1.setBackground(new java.awt.Color(245, 247, 250));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(76, 40));

        jMenuMaster.setBackground(new java.awt.Color(255, 255, 255));
        jMenuMaster.setForeground(new java.awt.Color(51, 51, 51));
        jMenuMaster.setText("Master");
        jMenuMaster.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jMenuMaster.setIconTextGap(20);
        jMenuMaster.setMargin(new java.awt.Insets(2, 20, 2, 20));

        jMenuItemInputDataBuku.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemInputDataBuku.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItemInputDataBuku.setText("Input Data Buku");
        jMenuItemInputDataBuku.setPreferredSize(new java.awt.Dimension(280, 30));
        jMenuItemInputDataBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInputDataBukuActionPerformed(evt);
            }
        });
        jMenuMaster.add(jMenuItemInputDataBuku);

        jMenuItemRegistrasiAnggota.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemRegistrasiAnggota.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItemRegistrasiAnggota.setText("Registrasi Anggota");
        jMenuItemRegistrasiAnggota.setPreferredSize(new java.awt.Dimension(280, 30));
        jMenuItemRegistrasiAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrasiAnggotaActionPerformed(evt);
            }
        });
        jMenuMaster.add(jMenuItemRegistrasiAnggota);

        jMenuItemRegistrasiPetugas.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemRegistrasiPetugas.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItemRegistrasiPetugas.setText("Registrasi Petugas");
        jMenuItemRegistrasiPetugas.setPreferredSize(new java.awt.Dimension(280, 30));
        jMenuItemRegistrasiPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrasiPetugasActionPerformed(evt);
            }
        });
        jMenuMaster.add(jMenuItemRegistrasiPetugas);

        jMenuBar1.add(jMenuMaster);

        jMenuTransaksi.setBackground(new java.awt.Color(255, 255, 255));
        jMenuTransaksi.setForeground(new java.awt.Color(51, 51, 51));
        jMenuTransaksi.setText("Transaksi");
        jMenuTransaksi.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jMenuTransaksi.setIconTextGap(20);
        jMenuTransaksi.setMargin(new java.awt.Insets(2, 20, 2, 20));
        jMenuTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuTransaksiMouseClicked(evt);
            }
        });
        jMenuTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTransaksiActionPerformed(evt);
            }
        });

        jMenuItemPeminjamanBuku.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemPeminjamanBuku.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItemPeminjamanBuku.setText("Peminjaman");
        jMenuItemPeminjamanBuku.setPreferredSize(new java.awt.Dimension(280, 30));
        jMenuItemPeminjamanBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPeminjamanBukuActionPerformed(evt);
            }
        });
        jMenuTransaksi.add(jMenuItemPeminjamanBuku);

        jMenuItemPengembalianBuku.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemPengembalianBuku.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItemPengembalianBuku.setText("Pengembalian");
        jMenuItemPengembalianBuku.setPreferredSize(new java.awt.Dimension(280, 30));
        jMenuItemPengembalianBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPengembalianBukuActionPerformed(evt);
            }
        });
        jMenuTransaksi.add(jMenuItemPengembalianBuku);

        jMenuBar1.add(jMenuTransaksi);

        jMenuLaporan.setBackground(new java.awt.Color(255, 255, 255));
        jMenuLaporan.setForeground(new java.awt.Color(51, 51, 51));
        jMenuLaporan.setText("Laporan");
        jMenuLaporan.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jMenuLaporan.setIconTextGap(20);
        jMenuLaporan.setMargin(new java.awt.Insets(2, 20, 2, 20));
        jMenuLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuLaporanMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuLaporan);

        jMenuLogout.setBackground(new java.awt.Color(255, 255, 255));
        jMenuLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenuLogout.setForeground(new java.awt.Color(51, 51, 51));
        jMenuLogout.setText("Exit");
        jMenuLogout.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jMenuLogout.setIconTextGap(40);
        jMenuLogout.setMargin(new java.awt.Insets(2, 20, 2, 20));
        jMenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLogoutActionPerformed(evt);
            }
        });

        jMenuItemLogout.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemLogout.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.setPreferredSize(new java.awt.Dimension(280, 30));
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenuLogout.add(jMenuItemLogout);

        jMenuBar1.add(jMenuLogout);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textfieldKodeBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldKodeBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldKodeBukuActionPerformed

    private void textfieldJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldJudulActionPerformed

    private void textfieldPengarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldPengarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldPengarangActionPerformed

    private void textfieldPenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldPenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldPenerbitActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        // TODO add your handling code here
        if(comboboxKategoriBuku.getSelectedItem().equals("") ||
           textfieldJudul.getText().equals("") ||
           textfieldPengarang.getText().equals("") ||
           textfieldPenerbit.getText().equals("") ||
           textfieldTahunTerbit.getText().equals("") ||
           textfieldKodeRak.getText().equals("") ||
           textfieldJumlah.getText().equals("") ||
           textfieldNamaFileBuku.getText().equals("") ||
           textfieldKodeBuku.getText().equals("")
        ){
            javax.swing.JOptionPane. showMessageDialog(null,"Data belum lengkap. \nSilahkan periksa kembali.",
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        }else{
            try {
                String sql = "UPDATE buku SET kategori_buku=?, judul_buku=?, pengarang=?, "
                        + "penerbit=?, tahun_terbit=?, kode_rak=?, jumlah=?, image=? where kode_buku=?";
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, comboboxKategoriBuku.getSelectedItem().toString());
                stat.setString(2, textfieldJudul.getText());
                stat.setString(3, textfieldPengarang.getText());
                stat.setString(4, textfieldPenerbit.getText());
                stat.setString(5, textfieldTahunTerbit.getText());
                stat.setString(6, textfieldKodeRak.getText());
                stat.setString(7, textfieldJumlah.getText());
                stat.setString(8, textfieldNamaFileBuku.getText());
                stat.setString(9, textfieldKodeBuku.getText());

                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil diubah");

                try {
                    String path=new File(".").getCanonicalPath();
                    FileUtils.copyFileToDirectory(file, new File(path+"/image")); //copy file ke folder image
                } catch (IOException ex) {
                    Logger.getLogger(FormInputBuku.class.getName()).log(Level.SEVERE, null, ex);
                }

                kosong();
                textfieldKodeBuku.requestFocus();
                datatable();

            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Diubah "+e);
            } 
        }
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        // TODO add your handling code here:
        if(comboboxKategoriBuku.getSelectedItem().equals("") ||
           textfieldJudul.getText().equals("") ||
           textfieldPengarang.getText().equals("") ||
           textfieldPenerbit.getText().equals("") ||
           textfieldTahunTerbit.getText().equals("") ||
           textfieldKodeRak.getText().equals("") ||
           textfieldJumlah.getText().equals("") ||
           textfieldNamaFileBuku.getText().equals("") ||
           textfieldKodeBuku.getText().equals("")
        ){
            javax.swing.JOptionPane. showMessageDialog(null,"Data belum lengkap. \nSilahkan periksa kembali.",
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        }else{
            String sql = "INSERT INTO buku VALUES (?,?,?,?,?,?,?,?,?)";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, comboboxKategoriBuku.getSelectedItem().toString());
                stat.setString(2, textfieldKodeBuku.getText());
                stat.setString(3, textfieldJudul.getText());            
                stat.setString(4, textfieldPengarang.getText());
                stat.setString(5, textfieldPenerbit.getText());
                stat.setString(6, textfieldTahunTerbit.getText());
                stat.setString(7, textfieldKodeRak.getText());
                stat.setString(8, textfieldJumlah.getText());
                stat.setString(9, textfieldNamaFileBuku.getText());

                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");

                try {
                    String path=new File(".").getCanonicalPath();
                    FileUtils.copyFileToDirectory(file, new File(path+"/image")); //copy file ke folder image
                } catch (IOException ex) {
                    Logger.getLogger(FormInputBuku.class.getName()).log(Level.SEVERE, null, ex);
                }

                kosong();
                textfieldKodeBuku.requestFocus();
                datatable();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan "+e);
            }
        }
    }                                     

    private void ignoreThisMethod(java.awt.event.MouseEvent evt) {                                          
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
                int ok = JOptionPane.showConfirmDialog(null, "Hapus?", "Konfirmasi Dialog",
                JOptionPane.YES_NO_CANCEL_OPTION);
        if(ok == 0){
            String sql = "DELETE FROM buku WHERE kode_buku='"+textfieldKodeBuku.getText()+"'";
            try{
                PreparedStatement stat =conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil dihapus");
                kosong();
                textfieldKodeBuku.requestFocus();
                datatable();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Data gagal dihapus "+e);
            }
       }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_buttonClearActionPerformed

    private void textfieldKodeRakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldKodeRakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldKodeRakActionPerformed

    private void textfieldJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldJumlahActionPerformed

    private void textfieldTahunTerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldTahunTerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldTahunTerbitActionPerformed

    private void tableBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBukuMouseClicked
        // TODO add your handling code here:
        int bar = tableBuku.getSelectedRow();
        String kode_buku = tabmode.getValueAt(bar, 0).toString();

        String sql = "SELECT * FROM buku WHERE kode_buku='"+ kode_buku +"'";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("kategori_buku");
                String b = hasil.getString("kode_buku");
                String c = hasil.getString("judul_buku");
                String d = hasil.getString("pengarang");
                String e = hasil.getString("penerbit");
                String f = hasil.getString("tahun_terbit");
                String g = hasil.getString("kode_rak");
                String h = hasil.getString("jumlah");
                String i = hasil.getString("image");
                 
                comboboxKategoriBuku.setSelectedItem(a);
                textfieldKodeBuku.setText(b);
                textfieldJudul.setText(c);
                textfieldPengarang.setText(d);
                textfieldPenerbit.setText(e);
                textfieldTahunTerbit.setText(f);
                textfieldKodeRak.setText(g);
                textfieldJumlah.setText(h);
                textfieldNamaFileBuku.setText(i);   
      
                //Untuk Ambil Gambar dari folder Image yang namanya ada di database
                try {
                    Toolkit toolkit=Toolkit.getDefaultToolkit();

                    String path=new File(".").getCanonicalPath();

                    Image image=toolkit.getImage(path+"/image/"+i); //mengambil gambar dari folder image
                    Image imagedResized=image.getScaledInstance(140, 170, Image.SCALE_DEFAULT); //resize foto sesuai ukuran jlabel
                    ImageIcon icon=new ImageIcon(imagedResized);
                    jLabelGambar.setIcon(icon); // memasang gambar pada jlabel
                }catch (IOException ex) {
                            Logger.getLogger(FormInputBuku.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }catch (SQLException e)     {
            
        }       
    }//GEN-LAST:event_tableBukuMouseClicked

    private void textfieldCariJudulBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldCariJudulBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldCariJudulBukuActionPerformed

    private void buttonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariActionPerformed
        // TODO add your handling code here:
        Object[] Baris = {"Kode Buku", "Judul", "Pengarang", 
            "Penerbit", "Jumlah"};
        tabmode = new DefaultTableModel(null, Baris);
        tableBuku.setModel(tabmode);
        String sql = "SELECT * FROM buku WHERE judul_buku like '%"+textfieldCariJudulBuku.getText()+"%'";

        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("kode_buku");
                String b = hasil.getString("judul_buku");
                String c = hasil.getString("pengarang");
                String d = hasil.getString("penerbit");
                String e = hasil.getString("jumlah");

                String[] data={a, b, c, d, e};
                tabmode.addRow(data);

            }
        }catch (SQLException e){                  
        }
    }//GEN-LAST:event_buttonCariActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
        datatable();
        textfieldCariJudulBuku.setText("");
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void jButtonPilihGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPilihGambarActionPerformed
        // TODO add your handling code here:
        jfc=new JFileChooser();
        if(jfc.showOpenDialog(jLabelGambar)==JFileChooser.APPROVE_OPTION){
            
            Toolkit toolkit=Toolkit.getDefaultToolkit();
            Image image=toolkit.getImage(jfc.getSelectedFile().getAbsolutePath());
            Image imagedResized=image.getScaledInstance(140, 170, Image.SCALE_DEFAULT);
            ImageIcon imageIcon=new ImageIcon(imagedResized);
            
            jLabelGambar.setIcon(imageIcon);
            textfieldNamaFileBuku.setText(jfc.getSelectedFile().getName());

            file=new File(jfc.getSelectedFile().getPath()); // file untuk dikopi
        }
    }//GEN-LAST:event_jButtonPilihGambarActionPerformed

    private void textfieldNamaFileBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldNamaFileBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldNamaFileBukuActionPerformed

    private void jMenuItemInputDataBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInputDataBukuActionPerformed
        // TODO add your handling code here:
        new FormInputBuku().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jMenuItemInputDataBukuActionPerformed

    private void jMenuItemRegistrasiAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrasiAnggotaActionPerformed
        // TODO add your handling code here:
        new FormRegistrasi().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jMenuItemRegistrasiAnggotaActionPerformed

    private void jMenuItemRegistrasiPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrasiPetugasActionPerformed
        // TODO add your handling code here:
        new FormPetugas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemRegistrasiPetugasActionPerformed

    private void jMenuItemPeminjamanBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPeminjamanBukuActionPerformed
        // TODO add your handling code here:
        new FormPeminjamanBuku().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemPeminjamanBukuActionPerformed

    private void jMenuItemPengembalianBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPengembalianBukuActionPerformed
        // TODO add your handling code here:
        new FormPengembalianBuku().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemPengembalianBukuActionPerformed

    private void jMenuTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuTransaksiMouseClicked
        // TODO add your handling code here:
        new FormPeminjamanBuku().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jMenuTransaksiMouseClicked

    private void jMenuTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuTransaksiActionPerformed

    private void jMenuLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuLaporanMouseClicked
        // TODO add your handling code here:
        new FormMasterLaporan().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jMenuLaporanMouseClicked

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        // TODO add your handling code here:
        new FormLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jMenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLogoutActionPerformed
        // TODO add your handling code here:
        new FormLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInputBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInputBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInputBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInputBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormInputBuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonCari;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonSave;
    private javax.swing.JComboBox<String> comboboxKategoriBuku;
    private javax.swing.JButton jButtonPilihGambar;
    private javax.swing.JLabel jLabelGambar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemInputDataBuku;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemPeminjamanBuku;
    private javax.swing.JMenuItem jMenuItemPengembalianBuku;
    private javax.swing.JMenuItem jMenuItemRegistrasiAnggota;
    private javax.swing.JMenuItem jMenuItemRegistrasiPetugas;
    private javax.swing.JMenu jMenuLaporan;
    private javax.swing.JMenu jMenuLogout;
    private javax.swing.JMenu jMenuMaster;
    private javax.swing.JMenu jMenuTransaksi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelEdisi;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelJumlah;
    private javax.swing.JLabel labelKategoriBuku;
    private javax.swing.JLabel labelKodeBuku;
    private javax.swing.JLabel labelKodeBuku1;
    private javax.swing.JLabel labelNama2;
    private javax.swing.JLabel labelPenerbit;
    private javax.swing.JLabel labelPengarang;
    private javax.swing.JLabel labelTahunTerbit;
    private javax.swing.JLabel labelTitle2;
    private javax.swing.JLabel labelTitle3;
    private javax.swing.JTable tableBuku;
    private javax.swing.JTextField textfieldCariJudulBuku;
    private javax.swing.JTextField textfieldJudul;
    private javax.swing.JTextField textfieldJumlah;
    private javax.swing.JTextField textfieldKodeBuku;
    private javax.swing.JTextField textfieldKodeRak;
    private javax.swing.JTextField textfieldNamaFileBuku;
    private javax.swing.JTextField textfieldPenerbit;
    private javax.swing.JTextField textfieldPengarang;
    private javax.swing.JTextField textfieldTahunTerbit;
    // End of variables declaration//GEN-END:variables
}
