/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author BrownBox
 */
public class FormDaftarPengunjung extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();

    /**
     * Creates new form FormRegistrasi
     */
    public FormDaftarPengunjung() {
        initComponents();
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        labelUsername = new javax.swing.JLabel();
        textfieldNama = new javax.swing.JTextField();
        buttonSimpan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        textfieldIDAnggota = new javax.swing.JTextField();
        labelUsername4 = new javax.swing.JLabel();
        comboboxKelas = new javax.swing.JComboBox<>();
        labelUsername6 = new javax.swing.JLabel();
        textfieldTujuan = new javax.swing.JTextField();
        labelUsername1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Perpustakaan");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 170, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelUsername.setFont(new java.awt.Font("Balsamiq Sans", 1, 24)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(255, 255, 255));
        labelUsername.setText("Nama Kamu");
        jPanel3.add(labelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        textfieldNama.setFont(new java.awt.Font("Balsamiq Sans", 1, 24)); // NOI18N
        textfieldNama.setToolTipText("");
        textfieldNama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldNamaActionPerformed(evt);
            }
        });
        jPanel3.add(textfieldNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 280, 40));

        buttonSimpan.setBackground(new java.awt.Color(71, 127, 255));
        buttonSimpan.setFont(new java.awt.Font("Balsamiq Sans", 1, 24)); // NOI18N
        buttonSimpan.setForeground(new java.awt.Color(255, 255, 255));
        buttonSimpan.setText("SIMPAN");
        buttonSimpan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 127, 255)));
        buttonSimpan.setBorderPainted(false);
        buttonSimpan.setMaximumSize(new java.awt.Dimension(70, 30));
        buttonSimpan.setMinimumSize(new java.awt.Dimension(70, 30));
        buttonSimpan.setPreferredSize(new java.awt.Dimension(70, 30));
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });
        buttonSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonSimpanKeyPressed(evt);
            }
        });
        jPanel3.add(buttonSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 250, 40));

        jLabel3.setBackground(new java.awt.Color(71, 127, 255));
        jLabel3.setFont(new java.awt.Font("Balsamiq Sans", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DATA PENGUNJUNG");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        textfieldIDAnggota.setFont(new java.awt.Font("Balsamiq Sans", 1, 24)); // NOI18N
        textfieldIDAnggota.setToolTipText("");
        textfieldIDAnggota.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldIDAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldIDAnggotaActionPerformed(evt);
            }
        });
        jPanel3.add(textfieldIDAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 280, 40));

        labelUsername4.setFont(new java.awt.Font("Balsamiq Sans", 1, 24)); // NOI18N
        labelUsername4.setForeground(new java.awt.Color(255, 255, 255));
        labelUsername4.setText("Kelas");
        jPanel3.add(labelUsername4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        comboboxKelas.setFont(new java.awt.Font("Balsamiq Sans", 1, 24)); // NOI18N
        comboboxKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        comboboxKelas.setBorder(null);
        comboboxKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxKelasActionPerformed(evt);
            }
        });
        jPanel3.add(comboboxKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 120, -1));

        labelUsername6.setFont(new java.awt.Font("Balsamiq Sans", 1, 24)); // NOI18N
        labelUsername6.setForeground(new java.awt.Color(255, 255, 255));
        labelUsername6.setText("Tujuan");
        jPanel3.add(labelUsername6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

        textfieldTujuan.setFont(new java.awt.Font("Balsamiq Sans", 1, 24)); // NOI18N
        textfieldTujuan.setToolTipText("");
        textfieldTujuan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldTujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldTujuanActionPerformed(evt);
            }
        });
        jPanel3.add(textfieldTujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 270, 40));

        labelUsername1.setFont(new java.awt.Font("Balsamiq Sans", 1, 24)); // NOI18N
        labelUsername1.setForeground(new java.awt.Color(255, 255, 255));
        labelUsername1.setText("ID Anggota Kamu");
        jPanel3.add(labelUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 560, 600));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/images/cover-pengunjung.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonSimpanKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSimpanKeyPressed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
                String sql = "INSERT INTO pengunjung VALUES (?,?,?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, textfieldIDAnggota.getText());
            stat.setString(2, textfieldNama.getText());
            stat.setString(3, comboboxKelas.getSelectedItem().toString());
            stat.setString(4, textfieldTujuan.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan. Selamat membaca!");
            kosong();
            textfieldIDAnggota.requestFocus();            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan "+e);
        }
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void textfieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldNamaActionPerformed

    private void textfieldIDAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldIDAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldIDAnggotaActionPerformed

    private void comboboxKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxKelasActionPerformed

    private void textfieldTujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldTujuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldTujuanActionPerformed

    protected void kosong(){
        textfieldIDAnggota.setText("");
        textfieldNama.setText("");
        comboboxKelas.setSelectedIndex(0);
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDaftarPengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDaftarPengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDaftarPengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDaftarPengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDaftarPengunjung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JComboBox<String> comboboxKelas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JLabel labelUsername1;
    private javax.swing.JLabel labelUsername4;
    private javax.swing.JLabel labelUsername6;
    private javax.swing.JTextField textfieldIDAnggota;
    private javax.swing.JTextField textfieldNama;
    private javax.swing.JTextField textfieldTujuan;
    // End of variables declaration//GEN-END:variables
}
