/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import java.io.IOException;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author BrownBox
 */
public class FormPengembalianBuku extends javax.swing.JFrame {
    private final Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;            

    /**
     * Creates new form FormTransaksi
     */
    public FormPengembalianBuku() {
        initComponents();
        datatable();
        jPanelStatus.setVisible(false);
        labelDenda.setVisible(false);
    }

    protected void kosong(){
        textfieldIDAnggota.setText("");
        textfieldIDTransaksi.setText("");
        textfieldKodeBuku.setText("");
        labelDenda.setText("");
    }
    protected void kosongkanDataBuku(){
        textfieldKodeBuku.setText("");
        labelJudulBuku.setText("-");
        textfieldKodeBuku.requestFocus();
    }
    protected void kosongkanDataAnggota(){
        textfieldIDAnggota.setText("");
        labelNama.setText("-");
        textfieldKodeBuku.requestFocus();
    }
    
    //Method mengetahui lama peminjaman buku
    //Jika lama peminjaman lewat dari tgl kembali, muncul warning merah
    protected void selisihTanggal(){
        try {
            java.util.Date tglSekarang = new java.util.Date();            
            java.util.Date tglPinjam = (java.util.Date) this.dateChooserTglPinjam.getDate();
            java.util.Date tglKembali = (java.util.Date) this.dateChooserTglKembali.getDate();
            
            System.out.println("Tanggal Pinjam : "+tglPinjam);
            System.out.println("Tanggal Kembali : "+tglKembali);            
            System.out.println("Tanggal Sekarang : "+tglSekarang);
            
            long tanggalSekarang = tglSekarang.getTime();
            long tanggalPinjam = tglPinjam.getTime();
            long tanggalKembali = tglKembali.getTime();

            long diff = tanggalSekarang - tanggalKembali;
            long lama = diff / (24 * 60 * 60 * 1000);            
            
            //Jika selisih tgl sekarang dengan tgl kembali lebih dari 1 hari
            //Maka akan muncul warning merah 
            if(lama > 1){
                jPanelStatus.setVisible(true);
                Long denda = lama*2000;
                labelLamaPinjam.setText(Long.toString(lama) + " hari, denda Rp"+denda);   
                labelDenda.setText(Long.toString(denda));
                System.out.println("lama :"+lama);    
                System.out.println("denda :"+denda);                    
            }
            
        } catch (Exception e) {
            System.out.println("" + e.getMessage());
        }
    }
  
    //Menampilkan data dari database ke table
    protected void datatable(){
        Object[] Baris = {"ID Transaksi", "Tgl Pinjam", "Tgl Kembali", "ID Anggota", 
            "Nama", "Kode Buku", "Judul Buku"};
        tabmode = new DefaultTableModel(null, Baris);
        tableTransaksiPeminjamanBuku.setModel(tabmode);
        String sql = "SELECT id_transaksi, tgl_pinjam, tgl_kembali, id_anggota, nama, "
                + "kode_buku, judul_buku FROM transaksi WHERE status='dipinjam'";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("id_transaksi");
                String b = hasil.getString("tgl_pinjam");
                String c = hasil.getString("tgl_kembali");
                String d = hasil.getString("id_anggota");
                String e = hasil.getString("nama");
                String f = hasil.getString("kode_buku");
                String g = hasil.getString("judul_buku");
                String[] data={a, b, c, d, e, f, g};
                tabmode.addRow(data);
            }
        }catch (SQLException e){                  
        }        
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelKodeBuku6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransaksiPeminjamanBuku = new javax.swing.JTable();
        labelTitle1 = new javax.swing.JLabel();
        panelAnggota1 = new javax.swing.JPanel();
        labelKodeBuku8 = new javax.swing.JLabel();
        labelKodeBuku7 = new javax.swing.JLabel();
        textfieldKodeBuku = new javax.swing.JTextField();
        labelJudulBuku = new javax.swing.JLabel();
        labelKodeBuku15 = new javax.swing.JLabel();
        labelKodeBuku = new javax.swing.JLabel();
        labelKodeBuku12 = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        textfieldIDAnggota = new javax.swing.JTextField();
        textfieldIDTransaksi = new javax.swing.JTextField();
        labelKodeBuku1 = new javax.swing.JLabel();
        dateChooserTglPinjam = new com.toedter.calendar.JDateChooser();
        dateChooserTglKembali = new com.toedter.calendar.JDateChooser();
        jPanelStatus = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelTerlambat1 = new javax.swing.JLabel();
        labelLamaPinjam = new javax.swing.JLabel();
        labelKodeBuku4 = new javax.swing.JLabel();
        labelKodeBuku16 = new javax.swing.JLabel();
        textfieldCariTransaksi = new javax.swing.JTextField();
        buttonCariTransaksi = new javax.swing.JButton();
        btnBukuKembali = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        labelDenda = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Peminjaman Buku");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 630));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelKodeBuku6.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelKodeBuku6.setForeground(new java.awt.Color(9, 110, 59));
        labelKodeBuku6.setText("Detail Transaksi");
        jPanel1.add(labelKodeBuku6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, -1, 20));

        tableTransaksiPeminjamanBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableTransaksiPeminjamanBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTransaksiPeminjamanBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTransaksiPeminjamanBuku);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 490, 300));

        labelTitle1.setBackground(new java.awt.Color(71, 127, 255));
        labelTitle1.setFont(new java.awt.Font("Montserrat SemiBold", 1, 24)); // NOI18N
        labelTitle1.setForeground(new java.awt.Color(9, 110, 59));
        labelTitle1.setText("Transaksi Pengembalian Buku");
        jPanel1.add(labelTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        panelAnggota1.setBackground(new java.awt.Color(255, 255, 255));
        panelAnggota1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        panelAnggota1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelKodeBuku8.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelKodeBuku8.setForeground(new java.awt.Color(153, 153, 153));
        labelKodeBuku8.setText("Judul Buku");
        panelAnggota1.add(labelKodeBuku8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 20));

        labelKodeBuku7.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelKodeBuku7.setForeground(new java.awt.Color(153, 153, 153));
        labelKodeBuku7.setText("Kode Buku");
        panelAnggota1.add(labelKodeBuku7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 20));

        textfieldKodeBuku.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldKodeBuku.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldKodeBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldKodeBukuActionPerformed(evt);
            }
        });
        panelAnggota1.add(textfieldKodeBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 190, 30));

        labelJudulBuku.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        labelJudulBuku.setText("-");
        panelAnggota1.add(labelJudulBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 190, 20));

        labelKodeBuku15.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelKodeBuku15.setForeground(new java.awt.Color(153, 153, 153));
        labelKodeBuku15.setText("ID Transaksi");
        panelAnggota1.add(labelKodeBuku15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 20));

        labelKodeBuku.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelKodeBuku.setForeground(new java.awt.Color(153, 153, 153));
        labelKodeBuku.setText("ID Anggota");
        panelAnggota1.add(labelKodeBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 20));

        labelKodeBuku12.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelKodeBuku12.setForeground(new java.awt.Color(153, 153, 153));
        labelKodeBuku12.setText("Nama");
        panelAnggota1.add(labelKodeBuku12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 20));

        labelNama.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        labelNama.setText("-");
        panelAnggota1.add(labelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 180, 20));

        textfieldIDAnggota.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldIDAnggota.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldIDAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldIDAnggotaActionPerformed(evt);
            }
        });
        panelAnggota1.add(textfieldIDAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 190, 30));

        textfieldIDTransaksi.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldIDTransaksi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldIDTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldIDTransaksiActionPerformed(evt);
            }
        });
        panelAnggota1.add(textfieldIDTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 190, 30));

        labelKodeBuku1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelKodeBuku1.setForeground(new java.awt.Color(153, 153, 153));
        labelKodeBuku1.setText("Tgl Pinjam");
        panelAnggota1.add(labelKodeBuku1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 20));
        panelAnggota1.add(dateChooserTglPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 150, -1));
        panelAnggota1.add(dateChooserTglKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 150, -1));

        jPanelStatus.setBackground(new java.awt.Color(255, 204, 204));
        jPanelStatus.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jPanelStatus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/images/exclamation-mark.png"))); // NOI18N
        jPanelStatus.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        labelTerlambat1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelTerlambat1.setForeground(new java.awt.Color(255, 51, 51));
        labelTerlambat1.setText("Pengembalian buku terlambat");
        jPanelStatus.add(labelTerlambat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        labelLamaPinjam.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelLamaPinjam.setForeground(new java.awt.Color(255, 51, 51));
        labelLamaPinjam.setText("Lama Pinjam");
        jPanelStatus.add(labelLamaPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 20));

        panelAnggota1.add(jPanelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 350, 70));

        labelKodeBuku4.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelKodeBuku4.setForeground(new java.awt.Color(153, 153, 153));
        labelKodeBuku4.setText("Tgl Kembali");
        panelAnggota1.add(labelKodeBuku4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, 20));

        jPanel1.add(panelAnggota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 410, 410));

        labelKodeBuku16.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelKodeBuku16.setForeground(new java.awt.Color(153, 153, 153));
        labelKodeBuku16.setText("Masukan ID Transaksi");
        jPanel1.add(labelKodeBuku16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        textfieldCariTransaksi.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldCariTransaksi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldCariTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldCariTransaksiActionPerformed(evt);
            }
        });
        jPanel1.add(textfieldCariTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 300, 30));

        buttonCariTransaksi.setBackground(new java.awt.Color(9, 110, 59));
        buttonCariTransaksi.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonCariTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        buttonCariTransaksi.setText("Cari");
        buttonCariTransaksi.setBorder(null);
        buttonCariTransaksi.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonCariTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariTransaksiActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCariTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 80, -1));

        btnBukuKembali.setBackground(new java.awt.Color(9, 110, 59));
        btnBukuKembali.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        btnBukuKembali.setForeground(new java.awt.Color(255, 255, 255));
        btnBukuKembali.setText("Mengembalikan Buku");
        btnBukuKembali.setBorder(null);
        btnBukuKembali.setPreferredSize(new java.awt.Dimension(75, 30));
        btnBukuKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBukuKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnBukuKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, 210, -1));

        buttonCancel.setBackground(new java.awt.Color(9, 110, 59));
        buttonCancel.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        buttonCancel.setForeground(new java.awt.Color(9, 110, 59));
        buttonCancel.setText("Cancel");
        buttonCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 127, 255)));
        buttonCancel.setContentAreaFilled(false);
        buttonCancel.setPreferredSize(new java.awt.Dimension(75, 30));
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        labelDenda.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        labelDenda.setForeground(new java.awt.Color(153, 153, 153));
        labelDenda.setText("0");
        jPanel1.add(labelDenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 540, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 28, -1, 590));

        jPanel3.setBackground(new java.awt.Color(212, 210, 212));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/images/cancel.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel3.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, -1));

        jLabel1.setBackground(new java.awt.Color(212, 210, 212));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/images/bar.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textfieldIDTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldIDTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldIDTransaksiActionPerformed

    private void textfieldKodeBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldKodeBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldKodeBukuActionPerformed

    private void textfieldIDAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldIDAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldIDAnggotaActionPerformed

    private void tableTransaksiPeminjamanBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTransaksiPeminjamanBukuMouseClicked
        // TODO add your handling code here:
        jPanelStatus.setVisible(false);
        labelDenda.setText("0");
        int bar = tableTransaksiPeminjamanBuku.getSelectedRow();
        String idTransaksi = tabmode.getValueAt(bar, 0).toString();
        String sql = "SELECT id_transaksi, id_anggota, nama, kode_buku, judul_buku,"
                + " tgl_pinjam, tgl_kembali FROM transaksi WHERE id_transaksi='"+idTransaksi+"'";        
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){    
                String a = hasil.getString("id_transaksi");                
                String b = hasil.getString("id_anggota");
                String c = hasil.getString("nama");
                String d = hasil.getString("kode_buku");
                String e = hasil.getString("judul_buku");
                String f = hasil.getString("tgl_pinjam");
                String g = hasil.getString("tgl_kembali");
                
                textfieldIDTransaksi.setText(a);
                textfieldIDAnggota.setText(b);            
                labelNama.setText(c);
                textfieldKodeBuku.setText(d);
                labelJudulBuku.setText(e); 
                //Convert dari String yang didapat dari sql ke Date
                try{            
                    java.util.Date tglPinjam = new SimpleDateFormat("yyyy-MM-dd").parse(f);
                    java.util.Date tglKembali = new SimpleDateFormat("yyyy-MM-dd").parse(g);         

                    dateChooserTglPinjam.setDate(tglPinjam);
                    dateChooserTglKembali.setDate(tglKembali);
                }catch(ParseException ex){
                    System.out.println("Date Parse Exception :"+ex);
                }
                
                selisihTanggal();

            }        
        }catch (SQLException e)     {
            JOptionPane.showMessageDialog(null, "Check SQL "+e);

       }    
    
    }//GEN-LAST:event_tableTransaksiPeminjamanBukuMouseClicked

    private void dateChooserTglPinjamPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateChooserTglPinjamPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_dateChooserTglPinjamPropertyChange

    private void dateChooserTglKembaliPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateChooserTglKembaliPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_dateChooserTglKembaliPropertyChange

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        new FormMenuUtama().setVisible(true);
        this.dispose();
   
    }//GEN-LAST:event_exitMouseClicked

    private void textfieldCariTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldCariTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldCariTransaksiActionPerformed

    private void buttonCariTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariTransaksiActionPerformed
        // TODO add your handling code here:
        Object[] Baris = {"ID Transaksi", "ID Anggota", "Nama", "NIS", 
            "Kode Buku", "Judul Buku"};
        tabmode = new DefaultTableModel(null, Baris);
        tableTransaksiPeminjamanBuku.setModel(tabmode);
        String sql = "SELECT id_transaksi, id_anggota, nama, kode_buku, judul_buku"
                + " FROM transaksi WHERE id_transaksi='"+textfieldCariTransaksi.getText()+"' AND status='dipinjam'";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("id_transaksi");                                
                String b = hasil.getString("id_anggota");                
                String c = hasil.getString("nama");
                String d = hasil.getString("kode_buku");
                String e = hasil.getString("judul_buku");
                
                String[] data={a, b, c, d, e};
                tabmode.addRow(data);
            }
        }catch (SQLException e){
                    
        }   
    }//GEN-LAST:event_buttonCariTransaksiActionPerformed

    private void btnBukuKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBukuKembaliActionPerformed
        // TODO add your handling code here:
        java.util.Date tglKembali = (java.util.Date) this.dateChooserTglKembali.getDate();  
        try{
            String sql = "UPDATE transaksi SET status='kembali', tgl_kembali=?, denda=? where id_transaksi=?";
       
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setDate(1, new Date(tglKembali.getTime()));            
            stat.setString(2, labelDenda.getText());            
            stat.setString(3, textfieldIDTransaksi.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Transaksi Sukses!");
            
            try {
                    //Cari jumlah buku di database
                    String kodeBuku = textfieldKodeBuku.getText();
                    System.out.println("Kode buku :"+kodeBuku);
                    
                    String sqlStockBuku = "SELECT jumlah FROM buku where kode_buku='"+kodeBuku+"'";
                    java.sql.Statement statStockBuku = conn.createStatement();
                    ResultSet hasilStockBuku = statStockBuku.executeQuery(sqlStockBuku);
                    
                    while(hasilStockBuku.next()){
                        int jumlahBuku = Integer.parseInt(hasilStockBuku.getString("jumlah"));
                        
                        try{
                            
                            //Karena Transaksi Berhasil maka, Stock Buku Bertambah 1
                            String sqlUpdateStock = "UPDATE buku SET jumlah=? where kode_buku='"+kodeBuku+"'";
                            PreparedStatement statment = conn.prepareStatement(sqlUpdateStock);
                            System.out.println("Jumlah Buku sebelum : "+jumlahBuku);

                            int x = jumlahBuku + 1;
                            String jumlahStockAkhir = Integer.toString(x);
                            statment.setString(1, jumlahStockAkhir);
                            System.out.println("Jumlah Buku sesudah : "+x);

                            statment.executeUpdate();
                            JOptionPane.showMessageDialog(null, "Stock bertambah 1");
                        }catch (SQLException e){
                            JOptionPane.showMessageDialog(null, "Check SQL "+e);
                       } 
                    }
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null, "Data Gagal bertambah"+e);
                }
            datatable();
            textfieldCariTransaksi.requestFocus();
            kosong();  
            kosongkanDataAnggota();
            kosongkanDataBuku(); 
            jPanelStatus.setVisible(false);

        }catch (SQLException e)     {
            JOptionPane.showMessageDialog(null, "Check SQL "+e);
       } 
    }//GEN-LAST:event_btnBukuKembaliActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
        datatable();
        textfieldCariTransaksi.setText("");
    }//GEN-LAST:event_buttonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPengembalianBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPengembalianBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPengembalianBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPengembalianBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPengembalianBuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBukuKembali;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonCariTransaksi;
    private com.toedter.calendar.JDateChooser dateChooserTglKembali;
    private com.toedter.calendar.JDateChooser dateChooserTglPinjam;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDenda;
    private javax.swing.JLabel labelJudulBuku;
    private javax.swing.JLabel labelKodeBuku;
    private javax.swing.JLabel labelKodeBuku1;
    private javax.swing.JLabel labelKodeBuku12;
    private javax.swing.JLabel labelKodeBuku15;
    private javax.swing.JLabel labelKodeBuku16;
    private javax.swing.JLabel labelKodeBuku4;
    private javax.swing.JLabel labelKodeBuku6;
    private javax.swing.JLabel labelKodeBuku7;
    private javax.swing.JLabel labelKodeBuku8;
    private javax.swing.JLabel labelLamaPinjam;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelTerlambat1;
    private javax.swing.JLabel labelTitle1;
    private javax.swing.JPanel panelAnggota1;
    private javax.swing.JTable tableTransaksiPeminjamanBuku;
    private javax.swing.JTextField textfieldCariTransaksi;
    private javax.swing.JTextField textfieldIDAnggota;
    private javax.swing.JTextField textfieldIDTransaksi;
    private javax.swing.JTextField textfieldKodeBuku;
    // End of variables declaration//GEN-END:variables
}
