/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author BrownBox
 */
public final class FormMenuPengunjung extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;    

    /**
     * Creates new form FormMenuUtama
     */
    public FormMenuPengunjung() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        data_pencarianBuku = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabelPencarianBuku = new javax.swing.JLabel();
        data_pengunjung = new javax.swing.JPanel();
        jLabelBukuPengunjung = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabelLoginPetugas = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menu Utama");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1000, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 247, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        data_pencarianBuku.setBackground(new java.awt.Color(251, 159, 196));
        data_pencarianBuku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        data_pencarianBuku.setPreferredSize(new java.awt.Dimension(200, 200));
        data_pencarianBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                data_pencarianBukuMouseClicked(evt);
            }
        });
        data_pencarianBuku.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(71, 127, 255));
        jLabel7.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(119, 51, 74));
        jLabel7.setText("Pencarian Buku");
        data_pencarianBuku.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabelPencarianBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/images/pencarianBuku.png"))); // NOI18N
        jLabelPencarianBuku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelPencarianBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPencarianBukuMouseClicked(evt);
            }
        });
        data_pencarianBuku.add(jLabelPencarianBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 100, 120));

        jPanel1.add(data_pencarianBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 200, 170));

        data_pengunjung.setBackground(new java.awt.Color(255, 216, 87));
        data_pengunjung.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        data_pengunjung.setPreferredSize(new java.awt.Dimension(200, 200));
        data_pengunjung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                data_pengunjungMouseClicked(evt);
            }
        });
        data_pengunjung.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBukuPengunjung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/images/bukuPengunjung.png"))); // NOI18N
        data_pengunjung.add(jLabelBukuPengunjung, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 110, 100));

        jLabel20.setBackground(new java.awt.Color(71, 127, 255));
        jLabel20.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(56, 14, 5));
        jLabel20.setText("Buku Pengunjung");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        data_pengunjung.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jPanel1.add(data_pengunjung, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 200, 170));

        jLabelLoginPetugas.setBackground(new java.awt.Color(71, 127, 255));
        jLabelLoginPetugas.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabelLoginPetugas.setForeground(new java.awt.Color(51, 51, 51));
        jLabelLoginPetugas.setText("Login Petugas");
        jLabelLoginPetugas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLoginPetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLoginPetugasMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelLoginPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, -1, 50));

        jLabel19.setBackground(new java.awt.Color(71, 127, 255));
        jLabel19.setFont(new java.awt.Font("Montserrat SemiBold", 0, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Perpustakaan ");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, 40));

        jLabel21.setBackground(new java.awt.Color(71, 127, 255));
        jLabel21.setFont(new java.awt.Font("Montserrat SemiBold", 0, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("MI Assa'adiyah Attahiriyah");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, 50));

        jLabel22.setBackground(new java.awt.Color(71, 127, 255));
        jLabel22.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Copyright 2020  |");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, -1, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/images/bg_menu_pengunjung.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void data_pencarianBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_pencarianBukuMouseClicked
        // TODO add your handling code here:
        new FormPencarianBuku().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_data_pencarianBukuMouseClicked

    private void jLabelPencarianBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPencarianBukuMouseClicked
        // TODO add your handling code here:
        new FormPencarianBuku().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelPencarianBukuMouseClicked

    private void data_pengunjungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_pengunjungMouseClicked
        // TODO add your handling code here:
        new FormDaftarPengunjung().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_data_pengunjungMouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        new FormDaftarPengunjung().setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabelLoginPetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginPetugasMouseClicked
        // TODO add your handling code here:
        new FormLogin().setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_jLabelLoginPetugasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenuPengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenuPengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenuPengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenuPengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenuPengunjung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel data_pencarianBuku;
    private javax.swing.JPanel data_pengunjung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelBukuPengunjung;
    private javax.swing.JLabel jLabelLoginPetugas;
    private javax.swing.JLabel jLabelPencarianBuku;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
