/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author BrownBox
 */
public class FormLogin extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();

    /**
     * Creates new form FormRegistrasi
     */
    public FormLogin() {
        initComponents();
    }
    private void loginMethod(){
        try{
            String sql = "SELECT * FROM petugas WHERE "
                    + "username='"+textfieldUsername.getText()
                    + "' AND password='"+jPasswordField.getText()+"'";
            
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            
            if(hasil.next()){
                if(textfieldUsername.getText().equals(hasil.getString("username")) &&
                        jPasswordField.getText().equals(hasil.getString("password")))
                {
                    new FormMenuUtama().setVisible(true);
                    this.dispose();
                }
            }else{
                JOptionPane.showMessageDialog(null, "Username atau Password Salah!");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }        
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelUsername2 = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        textfieldUsername = new javax.swing.JTextField();
        buttonLogin = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();
        labelUsername3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Perpustakaan");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(9, 110, 59));
        jLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(9, 110, 59));
        jLabel1.setText("Hi!");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        labelUsername2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelUsername2.setForeground(new java.awt.Color(188, 193, 202));
        labelUsername2.setText("Password");
        jPanel3.add(labelUsername2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        labelUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(188, 193, 202));
        labelUsername.setText("Username");
        jPanel3.add(labelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        textfieldUsername.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        textfieldUsername.setToolTipText("");
        textfieldUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 231, 232)));
        textfieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldUsernameActionPerformed(evt);
            }
        });
        jPanel3.add(textfieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 250, 30));

        buttonLogin.setBackground(new java.awt.Color(9, 110, 59));
        buttonLogin.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        buttonLogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogin.setText("LOGIN");
        buttonLogin.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        buttonLogin.setBorderPainted(false);
        buttonLogin.setMaximumSize(new java.awt.Dimension(70, 30));
        buttonLogin.setMinimumSize(new java.awt.Dimension(70, 30));
        buttonLogin.setPreferredSize(new java.awt.Dimension(70, 30));
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        buttonLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonLoginKeyPressed(evt);
            }
        });
        jPanel3.add(buttonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 250, 40));

        buttonCancel.setBackground(new java.awt.Color(255, 255, 255));
        buttonCancel.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        buttonCancel.setForeground(new java.awt.Color(9, 110, 59));
        buttonCancel.setText("CANCEL");
        buttonCancel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(9, 110, 59), 1, true));
        buttonCancel.setContentAreaFilled(false);
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        jPanel3.add(buttonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 250, 40));

        jPasswordField.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jPasswordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 231, 232), 1, true));
        jPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldKeyPressed(evt);
            }
        });
        jPanel3.add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 250, 30));

        labelUsername3.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        labelUsername3.setForeground(new java.awt.Color(190, 192, 205));
        labelUsername3.setText("Masukan username dan password.");
        jPanel3.add(labelUsername3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 560, 600));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/images/cover.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textfieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldUsernameActionPerformed

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        // TODO add your handling code here:
        loginMethod();
    }//GEN-LAST:event_buttonLoginActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonLoginKeyPressed
        // TODO add your handling code here:
        int code = evt.getKeyCode();
        if(code == evt.VK_ENTER){
            loginMethod();
        }        
    }//GEN-LAST:event_buttonLoginKeyPressed

    private void jPasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldKeyPressed
        // TODO add your handling code here:
        int code = evt.getKeyCode();
        if(code == evt.VK_ENTER){
            loginMethod();
        }
    }//GEN-LAST:event_jPasswordFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JLabel labelUsername2;
    private javax.swing.JLabel labelUsername3;
    private javax.swing.JTextField textfieldUsername;
    // End of variables declaration//GEN-END:variables
}
